### ISSUE TITLE
DLT Core Dump Handling

### ISSUE THREAD

**Issue by NikolayCheliuk** [COVESA/dlt-daemon#243]
Hi guys!

i want to try the DLT core dump processing mechanism. We read doc files and tried to follow guidelines but seems I miss something.

I read this manual:
    https://github.com/GENIVI/dlt-daemon/blob/master/doc/dlt_cdh.md
and have built dlt with next cmake command:
    cmake ../ -DWITH_DLT_COREDUMPHANDLER="ON" -DTARGET_CPU_NAME="x86_64" -DWITH_DLT_SYSTEM="ON" -DWITH_DLT_FILETRANSFER="ON"

Then we have updated dlt-system.conf according to the guidelines. But it didn't have an effect. I ran an example which was crashing and didn't see any specific log messages.

However I launched dlt-test-filetransfer and received a messages with the binary data. Seems dlt filetransfer works fine. Seems one thing is still needed form me. I have to build friendship between dlt filetransfer and dlt core dump handler.

Maybe I'm doing something unnecessary :)
I would be glad to get clear instruction how to configure the DLT system so to be able overview core dump info about died application with the DLT Viewer. It would be nice to know a list of necessary DLT components which should be built and launched too.

Best regards and have a nice day,
Nikolay Cheliuk

**Comment by NikolayCheliuk** [comment]
Seems dlt-cdh works correctly because when my app crashes the dump files are created in /var/core folder.
Hmm...
Seems we have got success but... 
When we started dlt-system with -d flag the file transfer didn't woek. After we have started dlt-system without -d flag a core files began to be transmitted.

Do you have any ideas why is it so?

**Comment by ssugiura** [comment]
@NikolayCheliuk Sorry for my late reply. Actually -d flag needs improvement, as current DLT prohibits using APIs from forked child process, and -d flag does use it. So from latest code, it is expected that it doesn't work.

**Comment by thanhbnq** [comment]
Hello @NikolayCheliuk ,

If you have your own solution for this issue, please help to raise PR and we are willing to incorporate your work.
By the way, I would like to close this issue since we do not have more discussion.

Thank you very much,
Thanh
