### ISSUE TITLE
Lines are hex instead of text

### ISSUE THREAD

**Issue by NicoSchirmeier** [COVESA/dlt-daemon#249]
Hi. I don´t know wether this is a common issue, but I use the dlt-convert feature of the demon to convert dlt files into log files for filebeat to be read. Some of the lines having the same line number in the original file are converted into hex lines. So the initial line looks kinda like this: 
(line number) (some tags) message
and the output would then look like:
(line number) (some tags) hex code 

While the line numbers and tags are equal. Is this behaviuer common and does this look like a conversion problem or could it be more of an filebeat/logstash/elastic issue or otherwise an issue inside the dlt ? 

btw. this doesn´t apply to all lines. some are looking fine while others aren´t. There are log lines containing hex inside the log file but not as much as there are after conversion.

**Comment by ssugiura** [comment]
@NicoSchirmeier Sorry for my late reply. Which option did you give to dlt-convert to get hex lines?

**Comment by NicoSchirmeier** [comment]
@ssugiura we later on noticed our viewer contained plugins to read these specific lines. These are yet to be integrated into our conversion process

**Comment by thanhbnq** [comment]
Hello @NicoSchirmeier ,

Based on your latest comment, I think this issue was resolved by your configuration/ plugin. 
So I'd like to close this issue. In case you have any further concerns, please open the new one.

Thank you,
Thanh
