### ISSUE TITLE
How to catch a packet

### ISSUE THREAD

**Issue by shtry** [COVESA/dlt-daemon#273]
Hi.

tcpdump doesn't seem to catch anything.

my command:

```
 ./dlt-daemon
```

```
 ./dlt-example-user 11111
Send 0 11111
Log level changed of context TEST, LogLevel=4, TraceState=0
Log level changed of context TS1, LogLevel=4, TraceState=0
Log level changed of context TS2, LogLevel=4, TraceState=0
Send 1 11111
Client disconnected!
Send 2 11111
Send 3 11111
Send 4 11111
Send 5 11111
Send 6 11111
Send 7 11111
Send 8 11111
```

```
tcpdump port 3490
tcpdump: verbose output suppressed, use -v
```

Thank you.

**Comment by ssugiura** [comment]
@shtry I guess you need to specify interface to monitor. E.g. If it's localhost, you can do `tcpdump -i lo port 3490`.

**Comment by shtry** [comment]
Thanks. @ssugiura 

I succeeded in catching the packet.

However, you cannot see the filter in wireshark.

Do you know why?

Wireshark appears to support DLT.

: https://www.wireshark.org/docs/dfref/d/dlt.html

But only TCP exists in my screenshot.

: 
![image](https://user-images.githubusercontent.com/75057700/105801222-0833fa00-5fdc-11eb-814a-64ce6c0d3f7d.png)


My pcap file : 
[test.zip](https://github.com/GENIVI/dlt-daemon/files/5871214/test.zip)

**Comment by zeerd** [comment]
`ctrl+shift+p` -> `protocol` -> `DLT` . Check the ports there, they might be 0 by default.

**Comment by thanhbnq** [comment]
Hello @shtry ,

I guess this issue was resolved by comments/ supports from experts here. I'd like to close this issue and in case you have any further concerns, please create a new one.

Happy coding.
Thanh
