### ISSUE TITLE
Install on MacOS

### ISSUE THREAD

**Issue by PickHub** [COVESA/dlt-daemon#286]
Is it possible to run this on a Mac?

I'm getting this from make:
```
build git:(master) make
[  1%] Linking C shared library libdlt.dylib
ld: library not found for -lsocket
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/lib/libdlt.2.18.6.dylib] Error 1
make[1]: *** [src/lib/CMakeFiles/dlt.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by doabigcheese** [comment]
-lsocket not necessary on my, just open your link.txt in 
dlt-daemon/build/src/lib/CMakeFiles/dlt.dir/link.txt
and remove it, then it should work (at least it did for me)

**Comment by sincethenn** [comment]
> Thanks that helped. However now I'm getting:
> 
> ```
> dlt-daemon.c:1363:23: error: use of undeclared identifier 'F_SETPIPE_SZ'
> dlt-daemon.c:1368:32: error: use of undeclared identifier 'F_GETPIPE_SZ'
> ```
> 
> I tried [this](https://stackoverflow.com/questions/25411892/f-setpipe-sz-undeclared), which didn't work.

same issue with you. Have you resolved this issue?

**Comment by ssugiura** [comment]
I do not have tried on Mac unfortunately. Does it support unix socket? If so, you can compile with unix socket instead of FIFO by setting `DLT_IPC=UNIX_SOCKET` to avoid the issue.

**Comment by sumitpaulde** [comment]
> > Thanks that helped. However now I'm getting:
> > ```
> > dlt-daemon.c:1363:23: error: use of undeclared identifier 'F_SETPIPE_SZ'
> > dlt-daemon.c:1368:32: error: use of undeclared identifier 'F_GETPIPE_SZ'
> > ```
> > 
> > 
> > I tried [this](https://stackoverflow.com/questions/25411892/f-setpipe-sz-undeclared), which didn't work.
> 
> same issue with you. Have you resolved this issue?

I am also having the same issue while installing it on Mac, any update regarding installation?

**Comment by thanhbnq** [comment]
Hello everyone,

It seems there were no more concerns/ discussion on this topic. I'd like to close this issue.
In case you want to have further discussion or you already had solution please create new issue or PR to share with community.

Happy coding,
Thanh

**Comment by lanbaoshen** [comment]
@sincethenn  @ssugiura 
I am trying to gradually fix `make` errors on macOS, and it has been successfully compiled on **Apple Silicon** so far. Perhaps you can give it a try [lanbaoshen/dlt-daemon-macos](https://github.com/lanbaoshen/dlt-daemon-macos)
<img width="430" alt="image" src="https://github.com/COVESA/dlt-daemon/assets/101860174/35f86f18-7db4-4cc4-891e-7d2008e7642a">
