### ISSUE TITLE
Is it possible to port dlt-daemon into RTOS ?

### ISSUE THREAD

**Issue by 0xkelvin** [COVESA/dlt-daemon#303]

**Comment by thanhbnq** [comment]
Hello @vietmaiquoc ,

Glad to receive your question!
Unfortunately, so far, I have no opportunities to experience DLT and RTOS.

Have you had any chances to prepare some changes for this at your side ?
If yes, please kindly share with us via PR!

Thank you in advance and sorry for late in response!
Thanh

**Comment by thanhbnq** [comment]
I would like to close this topic since there is no updates from reporter
