### ISSUE TITLE
Coverity error with every DLT_LOG()

### ISSUE THREAD

**Issue by sucharitasamanta** [COVESA/dlt-daemon#308]
We have coverity check for our project and wherever we have used DLT log print, on those lines we get an error. We have coverity errors 1572 in total, out of these 885 is for DLT_LOG(). 

![image](https://user-images.githubusercontent.com/83828025/117469670-9f153880-af73-11eb-8c72-f0f554fe949a.png)

https://github.com/GENIVI/dlt-daemon/blob/e969bed805f7dba9d2fa35c56a7ace28efb67e4e/include/dlt/dlt_user_macros.h#L224

Here I can see there is a suggestion to avoid `comma operator` misra warning. It will be very helpful if something can be done to fix `AUTOSAR C++14 A5-0-2 | autosar_cpp14_a5_0_2_violation` coverity error. There will be significant reduction in misra/coverity issues

**Comment by michael-methner** [comment]
No response from reporter -> closing.

**Comment by sucharitasamanta** [comment]
If the while condition is made to be false. But I am not sure if this breaks other logic.
do { 
....
....

    } while(**false**)
