### ISSUE TITLE
dlt-daemon qnx bind() error

### ISSUE THREAD

**Issue by jjaf-projects** [COVESA/dlt-daemon#328]
Hi, 

I'm having some issues launching dlt-daemon on my QNX board running QNX 7.0. 

The issue is the following:

![image](https://user-images.githubusercontent.com/4526563/133147850-1ccd4cca-5760-479c-8464-1ad427e44c3c.png)

I'm building dlt-daemon with the following cmake flags:
`-DBUILD_SHARED_LIBS=ON -DWITH_DLT_SYSTEM=OFF -DWITH_DLT_DBUS=OFF -DDLT_IPC=UNIX_SOCKET -DWITH_DLT_KPI=OFF -DWITH_DLT_USE_IPv6=OFF -DWITH_MAN=OFF`

I'm building the latest master. 

Maybe someone faced this issue before ? 
I already tried to change to another port but no luck. 

Thanks in advance.

**Comment by sebastienraillet** [comment]
Hi @jjaf-projects 👋🏼

Seems dlt-daemon isn't able to "create" the application socket (the one used between libdlt and dlt-daemon). If I'm not wrong, by default, this socket is created on _/tmp_ until you change this compilation option.

Check if _/tmp_ is mounted (or exist) on your system and you have rights to create a socket in that location 🙂

**Comment by thanhbnq** [comment]
Hi @jjaf-projects ,

Do you have any updates based on comment of @sebastienraillet ?

Thanh

**Comment by thanhbnq** [comment]
Hello all,
I would like to close this issue since there is no further concern.
Thank you,
Thanh
