### ISSUE TITLE
dlt file transfer feature is not fully reliable

### ISSUE THREAD

**Issue by anoojgopi** [COVESA/dlt-daemon#34]
Most of the project depends on the reliable file transfer mechanism (for eg. core dump, screenshots etc), but unfortunately current genivi dlt implimentation does not support a reliable mechanism. A high trace load or a client connect/disconnect could cause file transfer data to be lost. Same time after deleting the file from .tosend directory a shutdown trigger can happen before the buffered traces reach logger/dlt-viewer. In short, there is no hand shake protocol/confirmation message from logger device/dlt-viewer back to dlt-system to assure the file has reached (from ECU to Logger) fully. This must be improved.

**Comment by anoojgopi** [comment]
A handshake protocol (to confirm the file has reached the logger device or dlt-viewer), has to be defined by genivi specification, so that vendors supplying data logger devices follow the same.

**Comment by jeremiah** [comment]
I'm closing https://at.projects.genivi.org/jira/browse/DLT-8 because the maintainer preference is to use GitHub issues.

**Comment by minminlittleshrimp** [comment]
Close due to no further discussion
