### ISSUE TITLE
Example to send messages from dlt file to dlt daemon

### ISSUE THREAD

**Issue by sarensw** [COVESA/dlt-daemon#343]
Hello 👋 ,

I just have a basic question about this repository. I'm looking for a way to load an existing dlt file (valid one) and send the dlt message from this file to the dlt-deamon from this repo. I was able to build the deamon, pack this in a docker container, and run the dlt-example-user program to feed data into the daemon. However, I want to load a dlt file and push its messages into the dlt daemon instead. I searched the repo and found methods like dlt_file_open, and dlt_file_read. But as I'm not really a C++ dev, I struggle with this.

Therefore the question: Is there an example or a simple way on how to achieve this?

Regards, Stephan

**Comment by thanhbnq** [comment]
Hello @sarensw ,

Thank you very much for your question and sorry for our late response.

First of all, I would like to clarify that "dlt_file_open", "dlt_file_read" are about the APIs help for parsing a dlt file to human readable text. So I think it would not help in your case.

Secondly, if I understand your scenario correctly, all the thing you want is to transfer a file via dlt. If that is the case, I would propose one of our console binary which may help: dlt_filetransfer
Please kindly refer to this page for more details:
https://github.com/COVESA/dlt-daemon/blob/master/doc/dlt_filetransfer.md

Best regards,
Thanh

**Comment by thanhbnq** [comment]
Hello @sarensw ,

Do you have any updates on this topic?

Thanh

**Comment by sarensw** [comment]
Hi @thanhbnq , thanks for asking. Yes. The update is that I found a colleague who created such a simple dlt sever in Java. It loads a dlt file and runs through the messages as kind of a server. So I can connect with the dlt viewer to it and see the messages there.

**Comment by sarensw** [comment]
Closing this issue as it is not needed anymore.
