### ISSUE TITLE
DLT_INT/UINT macros adding unnecessary VARI bytes

### ISSUE THREAD

**Issue by andreirusu96** [COVESA/dlt-daemon#352]
Hello!

Unfortunately, the DLT Test User/Client suite fails because Test 2 (F/M).

The issue was introduced with https://github.com/COVESA/dlt-daemon/pull/292 and is caused by the current handling of DLT_INT/DLT_UINT macros.

After the introduction of the VARI attributes feature, while the specific calls to DLT_INT (for example, DLT_INT32) will call the correct function that will not involve the addition of VARI attributes:

`(void)dlt_user_log_write_int32(&log_local, INT_VAR) - No attribute`

The generic DLT_INT macro will call the "attributes" function with NULL arguments.

`dlt_user_log_write_uint() calls -> dlt_user_log_write_uint_attr(log, data, NULL, NULL); `

From the method description:

`If @a name is NULL, this function will add an attribute field with length 0 and no content to the message.`

![image](https://user-images.githubusercontent.com/16763553/141770027-7e577f49-dc88-486c-b697-17bc445e6842.png)

![image](https://user-images.githubusercontent.com/16763553/141769983-d9f02c38-f9ac-4c0f-86f3-cf9f8a4782b4.png)

As such, even though no attribute will be added, the VARI bit will be set (from Type Info DLT structure) and 4 bytes will be added to the payload, causing the aforementioned test 2 to fail.

![image](https://user-images.githubusercontent.com/16763553/141770086-923dffab-d480-48e0-a51a-48b429acb1f4.png)

![image](https://user-images.githubusercontent.com/16763553/141770136-a8c6b0e6-4192-4b14-9ba6-413830adfd04.png)

In my opinion, even though that from a DLT protocol point of view there is no issue, simply calling the generic DLT_INT instead of specific DLT_INT32 ( which should lead to the same result on a platform where sizeof(int) == 4 ) should not lead to the VARI bit being set and the 4 empty empty bytes being added.

**Solution:** dlt_user_log_write_uint() should not call dlt_user_log_write_uint_attr() anymore, but instead should have its own implementation that will call a specific dlt_user_log_write_uint*size*() depending on the size of INT. Here is an example: 

```
DltReturnValue dlt_user_log_write_uint(DltContextData *log, unsigned int data)
{
    return dlt_user_log_write_uint_attr(log, data, NULL, NULL);
    if (log == NULL)
        return DLT_RETURN_WRONG_PARAMETER;

    if (!dlt_user_initialised) {
        dlt_vlog(LOG_WARNING, "%s dlt_user_initialised false\n", __FUNCTION__);
        return DLT_RETURN_ERROR;
    }

    switch (sizeof(unsigned int)) {
    case 1:
    {
        return dlt_user_log_write_uint8(log, (uint8_t)data);
        break;
    }
    case 2:
    {
        return dlt_user_log_write_uint16(log, (uint16_t)data);
        break;
    }
    case 4:
    {
        return dlt_user_log_write_uint32(log, (uint32_t)data);
        break;
    }
    case 8:
    {
        return dlt_user_log_write_uint64(log, (uint64_t)data);
        break;
    }
    default:
    {
        return DLT_RETURN_ERROR;
        break;
    }
    }

    return DLT_RETURN_OK;
}
```

Of course, please let me know what is your opinion on this! Thanks!

**Comment by ssugiura** [comment]
@andreirusu96 
Yes, I totally agree with the idea. Let us take care of the fix. Thanks for raising this point!
