### ISSUE TITLE
DLT file transfer is looping/hanging for ever after some point of time in dlt_user_log_file_data .

### ISSUE THREAD

**Issue by srinivas-dama-harman** [COVESA/dlt-daemon#353]
Hello DLT Daemon support team,

Here is the problem we are facing with the dlt_user_log_file_complete API.

1. we are transferring binary files using the below code.
    int ret_info_dlt = dlt_user_log_file_infoAbout(&fileContext, file);
    if( ret_info_dlt != 0) {
        ALog("Error in dlt_user_log_file_infoAbout error %d",ret_info_dlt);
        remove(file);
    }
    else
    {
        int retTransfer = dlt_user_log_file_complete(&fileContext, file, true, 1);
        if(retTransfer != 0)
        {
            ALog("Error in dlt_user_log_file_complete error %d",retTransfer);
            remove(file);
        }
    }

2. After cetrain number of files (7 files) transfer, We have noticed that dlt_user_log_file_complete is getting hang for ever in dlt_user_log_file_data function in below while loop.
             while( !feof( file ) )
             {
                  //If the complete file should be transferred, the user buffer will be checked.
                  //If free space < 50% the package won't be transferred.
                 if(checkUserBufferForFreeSpace()>0)
                 {
                     pkgNumber++;
                     readBytes = fread(buffer, sizeof(char), BUFFER_SIZE, file);
                     int ok;
  
                     uint32_t fserial = getFileSerialNumber(filename,&ok);
  
                     if (1 != ok)
                     {
                         DLT_LOG(*fileContext,DLT_LOG_ERROR,
                         DLT_STRING("failed to get FileSerialNumber for: "),
                         DLT_STRING(filename));
                     }
  
                     DLT_LOG(*fileContext,DLT_LOG_INFO,
                             DLT_STRING("FLDA"),
                             DLT_UINT(fserial),
                             DLT_UINT(pkgNumber),
                             DLT_RAW(buffer,readBytes),
                             DLT_STRING("FLDA")
                     );
                 }
                 doTimeout(timeout);
             }

3. This is due to checkUserBufferForFreeSpace(). Below is the definition of checkUserBufferForFreeSpace. used_size value is more than (total_size/2). Due to this, this function is returning ‘-1’. Using gdb we saw that the value for “used_size” is not changing anymore when the erroneous situation is reached. Every loop it is exactly the same.

int checkUserBufferForFreeSpace()
{
    int total_size, used_size;

    dlt_user_check_buffer(&total_size, &used_size);

    if ((total_size - used_size) < (total_size / 2)) {
        return -1;
    }

    return 1;
}

Any one faced the similar issue? if so, Can you please provide the solution? Can you please help in this regard?
Please let me know if something is not clear or if you need more details .

Best regards,
Srinivasarao

**Comment by srinivas-dama-harman** [comment]
Hello there,
Can you please prioritize this issue?
regards,
Srinivasarao

**Comment by thanhbnq** [comment]
Hello @srinivas-dama-harman ,

Thank you very much for your detailed report!
I agree with you that the hanging is from the check of checkUserBufferForFreeSpace

For the quick proposal of solution, could you please kindly verify my following patch:

```
$ git df
diff --git a/src/lib/dlt_filetransfer.c b/src/lib/dlt_filetransfer.c
index bd196ea..db38323 100644
--- a/src/lib/dlt_filetransfer.c
+++ b/src/lib/dlt_filetransfer.c
@@ -642,6 +642,10 @@ int dlt_user_log_file_data(DltContext *fileContext, const char *filename, int pa
                             DLT_STRING("FLDA")
                             );
                 }
+                else {
+                    fclose(file);
+                    return DLT_FILETRANSFER_ERROR_FILE_DATA_USER_BUFFER_FAILED;
+                }

                 doTimeout(timeout);
             }
```

Best regards,
Thanh

**Comment by srinivas-dama-harman** [comment]
Hello @Thanh,

Thank you for the quick action and providing the patch. I've tested my code with this patch. Now, It is not hanging any more. But, the file transfer status in dlt-viewer is "Incomplete" for some of the files. It means, some data is missing in these files I believe.
Is there any other solution without loosing any data?

Best regards,
Srinivasarao.

**Comment by thanhbnq** [comment]
Hello @srinivas-dama-harman ,

Thanks for your verification!
Regarding the solution without loosing any data, I would propose you can adjust the size of buffer so that its size can be enough for your transferred files.
In order to do that, you can set via environment variables: `DLT_USER_BUFFER_MIN`, `DLT_USER_BUFFER_MAX`
Please be aware that its unit is bytes and `DLT_USER_BUFFER_MAX` must be larger than `DLT_USER_BUFFER_MIN` 
By default, `DLT_USER_BUFFER_MIN` is set as 50000 bytes ~ 50 KB. I guess that size is not enough for your case.

I hope it could help you.

Best regards,
Thanh
