### ISSUE TITLE
Cannot link DLT with my project using cmake

### ISSUE THREAD

**Issue by bilalmta** [COVESA/dlt-daemon#355]
When trying to add 

```
find_package(automotive-dlt REQUIRED)
target_link_libraries(${PROJECT_NAME} Genivi::DLT)
```

in my cmakelists file, there is an error saying:

 "Target "my_project" links to target "Genivi::DLT" but the target was not found.  Perhaps a find_package() call is missing for an IMPORTED target, or an ALIAS target is missing?"

What I could be missing?

**Comment by phongt** [comment]
@bilalmta the target_link_libraries() should be target_link_libraries(${PROJECT_NAME} Genivi::dlt)[1]

something like this work fine for me:

CMakeLists.txt
```
cmake_minimum_required(VERSION 3.15)
project(dltcheck)

find_package(automotive-dlt REQUIRED)

add_executable(${PROJECT_NAME} main.cc)
target_link_libraries(${PROJECT_NAME} Genivi::dlt)

```

[1]  https://github.com/COVESA/dlt-daemon/blob/master/automotive-dlt-config.cmake.in#L18

**Comment by bilalmta** [comment]
Thanks @phongt, actually the difference is in the lib name it's Genivi::dlt not Genivi::DLT

I think the readme should be updated to fix this "typo" maybe. 

Thanks for you help :)

**Comment by ssugiura** [comment]
@bilalmta 
Thanks for analyzing it already, do you mind raising PR to improve the point in Readme?

**Comment by bilalmta** [comment]
Sure,
I opened an issue here
You can find it here: https://github.com/COVESA/dlt-daemon/issues/365

I will fix it and make a PR.

**Comment by bilalmta** [comment]
> @bilalmta Thanks for analyzing it already, do you mind raising PR to improve the point in Readme?

I'm not able to push my branch to the repo it gives me this error:

remote: Permission to GENIVI/dlt-daemon.git denied to bilalmta.
fatal: unable to access 'https://github.com/GENIVI/dlt-daemon.git/': The requested URL returned error: 403

Do I have to do something special?

**Comment by ssugiura** [comment]
@bilalmta 
GENIVI is now rebranded to COVESA, which means github URL is also changed.
Please try it out to https://github.com/COVESA/dlt-daemon instead. Thanks!

**Comment by thanhbnq** [comment]
Hi @bilalmta,

Do you have any updates on this topic?

Thanh

**Comment by thanhbnq** [comment]
Thank you all for discussion.
I would like to close this issue since no more updates.
Thanh
