### ISSUE TITLE
disabling inject feature of DLT protocol

### ISSUE THREAD

**Issue by madmax440** [COVESA/dlt-daemon#360]
Hello,

Is there a way to disable inject feature of DLT protocol via compiler option? usecase is that i am trying to secure DLT from misuse / misconfigurations from the viewer. further would like to know if there is any authentication methods possible to access / connect to the DLT? or this is out of scope and is this going to be part of the Diagnostics?

thanks

**Comment by ssugiura** [comment]
@madmax440 
You can initially use option in dlt.conf: https://github.com/COVESA/dlt-daemon/blob/master/src/daemon/dlt.conf#L80
If you want to completely switch off using cmake option, I'd suggest to contribute from your end :)

**Comment by thanhbnq** [comment]
Hello @madmax440 ,
I would like to close this issue.
In case you already implemented some patches for your idea, please kindly create PR then we can together review.
Thank you both for discussion.
Thanh
