### ISSUE TITLE
Typo in the lib name in the README that will cause a linking error in the cmake

### ISSUE THREAD

**Issue by bilalmta** [COVESA/dlt-daemon#365]
In this Readme: https://github.com/COVESA/dlt-daemon/blob/master/doc/dlt_for_developers.md

Under this part **DLT with cmake**, the lib name should be **Genivi::dlt** not **Genivi::DLT**

If you tried to use the uppercase lib name it would give you a linking error.

**Comment by mawillers** [comment]
@bilalmta, please review the PR.
