### ISSUE TITLE
why Limit DLT_ID_SIZE ?

### ISSUE THREAD

**Issue by m1018** [COVESA/dlt-daemon#366]
我在代码中看见对于ECU和APPID 使用固定大小限制：#   define DLT_ID_SIZE 4
Is this a consideration?

**Comment by ssugiura** [comment]
@m1018 This is a requirement from AUTOSAR to limit the size to 4 bytes: https://www.autosar.org/fileadmin/user_upload/standards/classic/4-0/AUTOSAR_SWS_DiagnosticLogAndTrace.pdf
The latest protocol already extended the field to set longer IDs, but currently there's no plan to migrate.

**Comment by thanhbnq** [comment]
Thanks @ssugiura  for clarification.
@m1018  I would like to close this issue. If you have anything else to discuss further, please share with us.

Thanh
