### ISSUE TITLE
Reconnect dlt-receive

### ISSUE THREAD

**Issue by Nikhil-V-maker** [COVESA/dlt-daemon#370]
I have installed dlt-receive and using dlt-receive command in python subprocess module something like this
`dlt-receive -a <IP> -p <PORT> -s -o <filename.dlt>`
While the process is running in the background I have to perform a target system reboot and during the reboot I see the logging is getting stopped I don't see any further logs.
Is there any way so that I can reconnect to the process and continue logging after reboot?
Any help would be appreciated. Thank you

**Comment by thanhbnq** [comment]
Hello @Nikhil-V-maker ,

With the current implementation, dlt-receive does not support the re-connection feature.
Regarding your scenario, I would suggest two approaches:

1. Use offline logstorage feature. Please read more details at: https://github.com/COVESA/dlt-daemon/blob/master/doc/dlt_offline_logstorage.md 
2. Use a GUI-based dlt client, named dlt-viewer. It is supported the re-connection. Please read more details at: https://github.com/COVESA/dlt-viewer

Thanh

**Comment by thanhbnq** [comment]
@Nikhil-V-maker 
I would like to close this issue.
Thanh
