### ISSUE TITLE
Why DltContext struct has pointer?

### ISSUE THREAD

**Issue by Joe-Sangjo** [COVESA/dlt-daemon#371]
DltContext struct is dealt as pointer in DltContextData.
And DltContext has two pointer as memeber variable like below.

```
typedef struct
{
    char contextID[DLT_ID_SIZE];                  /**< context id */
    int32_t log_level_pos;                        /**< offset in user-application context field */
    int8_t *log_level_ptr;                        /**< pointer to the log level */
    int8_t *trace_status_ptr;                     /**< pointer to the trace status */
    uint8_t mcnt;                                 /**< message counter */
} DltContext;
```

Because log_level_ptr, trace_status_ptr is pointer, sometimes they become dangling pointer which cannot be detected with checking nullpointer when process is going to exit.

My question is why log level and trace status are pointer in DltContext?
How about make just value instead of pointer.?

**Comment by thanhbnq** [comment]
Hi @Joe-Sangjo ,
Well, you could be right in this point, it is maybe unnecessary to be a pointer for those attributes at all.
For now, due to backward compatibility, we should refer to fix dangling pointer if any instead of changing it.
We will improve it in future.
Thank you for discussion.
Thanh
