### ISSUE TITLE
Ported to qnx platform

### ISSUE THREAD

**Issue by EricMzky** [COVESA/dlt-daemon#374]
I want to port the whole system of dlt to qnx operating system, how can I do it? And ensure that daemon can be used, thank you

**Comment by EricMzky** [comment]
1. cmakelist :set qnx ON ,set complier = qcc and q++ path; 
2. cmake ok
3. make error:
[  1%] Building C object src/lib/CMakeFiles/dlt.dir/dlt_user.c.o
cc: Can't specify -P, -C, -E, -c or -S with -o and have multiple files
src/lib/CMakeFiles/dlt.dir/build.make:75: recipe for target 'src/lib/CMakeFiles/dlt.dir/dlt_user.c.o' failed
make[2]: *** [src/lib/CMakeFiles/dlt.dir/dlt_user.c.o] Error 1
CMakeFiles/Makefile2:322: recipe for target 'src/lib/CMakeFiles/dlt.dir/all' failed
make[1]: *** [src/lib/CMakeFiles/dlt.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by alexmohr** [comment]
The dlt-daemon is already ported to QNX, you'll have to all things systemd and build with `-DDLT_DAEMON_USE_UNIX_SOCKET_IPC`

Your error probably comes from an invalid compiler / toochain configuration as it doesn't support the flags passed to `cc`

**Comment by NeusoftZhangShuang** [comment]
for version 2.18.8, the option should be `-DDLT_IPC="UNIX_SOCKET"`

> The dlt-daemon is already ported to QNX, you'll have to disable all hings systemd and build with `-DDLT_DAEMON_USE_UNIX_SOCKET_IPC`
> 
> Your error probably comes from an invalid compiler / toochain configuration as it doesn't support the flags passed to `cc`

**Comment by thanhbnq** [comment]
Hello @EricMzky and @NeusoftZhangShuang 
I'd like to close this issue since we have no more concerns or discussion.
Please open new one if you need supports.
Thank you
