### ISSUE TITLE
Continue logging to the same file

### ISSUE THREAD

**Issue by Nikhil-V-maker** [COVESA/dlt-daemon#375]
My question is
When I use dlt receive command like below
`dlt-receive -a <ip> -p <port> -s -o <file_name>`
Each time it creates a new file. Is there a way I can continue logging to the same file or an already existing file?
Any help here would be appreciated, Thank you

**Comment by thanhbnq** [comment]
Hi @Nikhil-V-maker ,
In the current implementation, dlt-receive does not support to append the existing file with new logs.
We are happy and ready for review if you already implemented it and raise PR.
Thank you,
Thanh

**Comment by thanhbnq** [comment]
@Nikhil-V-maker I would like to close this discussion. In case you need any further support, please raise the new one.
