### ISSUE TITLE
Why not rotate to overwrite old log messages but to return DLT_RETURN_BUFFER_FULL when the ring-buffer is full

### ISSUE THREAD

**Issue by caiyuexiang** [COVESA/dlt-daemon#377]
In dlt_user.c, function: dlt_user_log_out_error_handling,  it will store log message in ring buffer if an error accured when failed to sending message to dlt daemon, and if the ring buffer is full, it will return  DLT_RETURN_BUFFER_FULL and discard new messages. 

What I'm confused about is the implementation is inconsistent with the description in the documentation dlt_design_specification.md, which is:
"- If the message could not be sent, store the message to a local ring buffer.
    The ring buffer internally uses a variable length for the buffered elements,
    and therefore uses the memory available for the buffer the best way possible.
    **If the buffer is full, the oldest messages are silently discarded, until
    there is enough space for the message to be stored in the ring buffer.**"

Did i miss something?
Any help here would be appreciated, Thank you

**Comment by cumtsmart** [comment]
I meet the same question. When i want to dump the last 2 minutes dlt log from ringbuffer, I found that ringbuffer will discard new coming dlt log when exceeding RingbufferMaxSize.

**Comment by minminlittleshrimp** [comment]
Answer: https://github.com/COVESA/dlt-daemon/issues/533
To-do: Correct the document
