### ISSUE TITLE
Why does the DLT_TYPE_INFO_STRG and DLT_SCOD_ASCII  not work properly ?

### ISSUE THREAD

**Issue by HaifengTony** [COVESA/dlt-daemon#386]
char buffer[512] = {0};
    size_t size = 0;
    int32_t args_num = 0;
    type_info = DLT_TYPE_INFO_STRG | DLT_SCOD_ASCII;
    memcpy(buffer + size, &(type_info), sizeof(uint32_t));
    size += sizeof(uint32_t);
    memcpy(buffer + size, "test11", sizeof("test11"));
    size += sizeof("test11");
    args_num++;

    if (dlt_user_log_write_start_w_given_buffer(&context, &contextData, DLT_LOG_WARN, buffer, size, args_num) > 0) {
        dlt_user_log_write_finish_w_given_buffer(&contextData);
    }

output:
      2022/06/15 16:59:11.587638 1707256955 001 ECU1 MAPP MCON log warn V 1 []

the failure:
     file:dlt-daemon/src/shared/dlt_common.c 
     func:dlt_message_argument_print
     line:3383/ DLT_MSG_READ_STRING(value_text, *ptr, *datalength, textlength, length);

**Comment by thanhbnq** [comment]
Hello @HaifengTony ,
Sorry for being late in response your issue.

Regarding the handling of string, dlt is providing the api dlt_user_log_write_string() which is more appropriate to use for your case.
By using dlt_user_log_write_string, the type_info will be handed properly then the macro DLT_MSG_READ_STRING can read/ parse the content successfully.

Best regards,
Thanh
