### ISSUE TITLE
Maintainers wanted?

### ISSUE THREAD

**Issue by alexmohr** [COVESA/dlt-daemon#388]
Pull requests are open a long time without being reviewed or merged. 
It seems like larger PRs are not even considered because the current maintainers do not have enough time to review them. 

What's the future plan for this repository? If you are on the lookout for new maintainers I'm sure people would sign up for that. Maybe 1-2 new maintainers could help the project and bring along some of the 15 PRs.

If you're accepting volunteers I'd personally be happy to help. Only drawback is that Mercedes-Benz currently is not a COVESA member. If that's an issue I'd also be willing to spend a bit of my personal time on this project.

**Comment by thanhbnq** [comment]
Hello @alexmohr ,
Thank you very much for raising this concern and really appreciate your enthusiasm when you volunteer for the role.
We would like to apologize since we are actually busy with project.
Your concern will be discussed and we will share the result with you/ community soon
Thanh
