### ISSUE TITLE
build QNX version

### ISSUE THREAD

**Issue by NeusoftZhangShuang** [COVESA/dlt-daemon#390]
i'm trying to build dlt-daemon 2.18.8 for a QNX board on an ubuntu PC.
i changed CMAKE_SYSTEM_NAME to QNX, then i got this:
`/media/share/hdd2t/samba_root/renzhong/qnx/apps/qnx_ap/ark/applications/cluster/SOC/dlt-daemon-2.18.8/src/daemon/dlt-daemon.c: In function 'dlt_daemon_init_fifo':
/media/share/hdd2t/samba_root/renzhong/qnx/apps/qnx_ap/ark/applications/cluster/SOC/dlt-daemon-2.18.8/src/daemon/dlt-daemon.c:1407:32: error: 'F_GETPIPE_SZ' undeclared (first use in this function)
     if ((fifo_size = fcntl(fd, F_GETPIPE_SZ, 0)) == -1)
                                ^
/media/share/hdd2t/samba_root/renzhong/qnx/apps/qnx_ap/ark/applications/cluster/SOC/dlt-daemon-2.18.8/src/daemon/dlt-daemon.c:1407:32: note: each undeclared identifier is reported only once for each function it appears in
dlt-daemon-2.18.8/src/daemon/CMakeFiles/dlt-daemon.dir/build.make:65: recipe for target 'dlt-daemon-2.18.8/src/daemon/CMakeFiles/dlt-daemon.dir/dlt-daemon.c.o' failed
make[6]: *** [dlt-daemon-2.18.8/src/daemon/CMakeFiles/dlt-daemon.dir/dlt-daemon.c.o] Error 1
CMakeFiles/Makefile2:656: recipe for target 'dlt-daemon-2.18.8/src/daemon/CMakeFiles/dlt-daemon.dir/all' failed
make[5]: *** [dlt-daemon-2.18.8/src/daemon/CMakeFiles/dlt-daemon.dir/all] Error 2
Makefile:132: recipe for target 'all' failed
make[4]: *** [all] Error 2
CMakeFiles/module.dir/build.make:96: recipe for target 'MAKE-MODULE' failed
make[3]: *** [MAKE-MODULE] Error 2
CMakeFiles/Makefile2:467: recipe for target 'CMakeFiles/module.dir/all' failed
make[2]: *** [CMakeFiles/module.dir/all] Error 2
CMakeFiles/Makefile2:474: recipe for target 'CMakeFiles/module.dir/rule' failed
make[1]: *** [CMakeFiles/module.dir/rule] Error 2
Makefile:206: recipe for target 'module' failed
make: *** [module] Error 2
`
how can i fix this?

after looking up issue list, i found that i'm not the only person who gets error when trying to build for QNX board, is it possible for you guys to write an official guid on how to build dlt-daemon for QNX environment?

**Comment by NeusoftZhangShuang** [comment]
i also added -DDLT_DAEMON_USE_UNIX_SOCKET_IPC=ON when i call `cmake ..` , but the error remains the same.

**Comment by thanhbnq** [comment]
Hello @NeusoftZhangShuang ,

Quickly check your error, the cmake option to specify the IPC mechanism is FIFO.
And the flag F_GETPIPE_SZ is not available in QNX.

I also see your comment in #374 . It looks like you found out the answer. Am I correct?
Regarding the instruction for QNX, we definitely need update them in README or appropriate place.
Just in case you are already having your update, please kindly raise PR.

Thanh

**Comment by NeusoftZhangShuang** [comment]
> Hello @NeusoftZhangShuang ,
> 
> Quickly check your error, the cmake option to specify the IPC mechanism is FIFO. And the flag F_GETPIPE_SZ is not available in QNX.
> 
> I also see your comment in #374 . It looks like you found out the answer. Am I correct? Regarding the instruction for QNX, we definitely need update them in README or appropriate place. Just in case you are already having your update, please kindly raise PR.
> 
> Thanh

i'm still working on it.
you mean you want me to write down how i build dlt for my QNX board?

**Comment by thanhbnq** [comment]
Hello @NeusoftZhangShuang ,

I thought you already had the answer from other discussions then I would expected a PR in which you help to update the instructions.

For now, I would like to share what we are doing with QNX compilation.

- Set cmake compiler to appropriate toolchain.
Example: 
set(CMAKE_C_COMPILER $QNX_HOST/usr/bin/aarch64-unknown-nto-qnx7.0.0-gcc)
set(CMAKE_CXX_COMPILER $QNX_HOST/usr/bin/aarch64-unknown-nto-qnx7.0.0-g++)

- Apply following CMake options (for QNX):
WITH_DLT_QNX_SYSTEM=ON  (I guess in your failure, you missed this option)
DLT_IPC=UNIX_SOCKET

Then do compilation.

Please kindly give it a try and share the result.
We will update the instructions for QNX very soon.
 
Thanh

**Comment by EricMzky** [comment]
Hello, there is still a problem with ddT-Daemon compiling QNX version, it has been configured : WITH_DLT_QNX_SYSTEM=ON
DLT_IPC=UNIX_SOCKET and set(CMAKE_C_COMPILER $QNX_HOST)
set(CMAKE_CXX_COMPILER $QNX_HOST)
But the following error occurs.When will a document be released on how to compile QNX ddT-Daemon and then run it successfully on ARM board and call DLT internal library

![2022-07-07_12-00](https://user-images.githubusercontent.com/37823382/177687845-52a944fb-85a0-4955-bf5f-ec70a0b299f0.png)

**Comment by EricMzky** [comment]
@thanhbnq

**Comment by EricMzky** [comment]
![Uploading 2022-07-07_12-02.png…]()

**Comment by EricMzky** [comment]
![2022-07-07_12-02](https://user-images.githubusercontent.com/37823382/177688031-f5273d82-70a5-4fe5-93d4-3a9e3a20c07c.png)

**Comment by EricMzky** [comment]
@NeusoftZhangShuang

**Comment by thanhbnq** [comment]
@EricMzky 
It looks like you are also compiling systemd binaries in QNX, it should be not.
Please add more following CMake options to your compilation and try again

```
WITH_SYSTEMD=OFF
WITH_SYSTEMD_WATCHDOG=OFF
WITH_SYSTEMD_JOURNAL=OFF
```
Regarding the instructions for QNX compilation, I would like to receive your good result first then PR will be raised based on your feedback.

**Comment by NeusoftZhangShuang** [comment]
@thanhbnq 
here is how i compile dlt-daemon 2.18.8:
1. setup QNX cross-compile environment
2. add this in root CMakeLists.txt: `set(CMAKE_SYSTEM_NAME 'QNX')`
3. change DLT_IPC to UNIX_SOCKET: `set(DLT_IPC "UNIX_SOCKET" CACHE STRING "UNIX_SOCKET,FIFO")`
4. turn on WITH_DLT_QNX_SYSTEM: `option(WITH_DLT_QNX_SYSTEM  "Set to ON to build QNX system binary dlt-qnx-system" ON)`
5. turn on WITH_DLT_SYSTEM: `option(WITH_DLT_SYSTEM "Set to ON to build src/system binaries" ON)`
6. turn on WITH_DLT_CXX11_EXT: `option(WITH_DLT_CXX11_EXT "Set to ON to build C++11 extensions" ON)`
7. turn off WITH_DLT_TESTS:`option(WITH_DLT_TESTS "Set to ON to build src/test binaries" OFF)`
then you can `mkdir build;cmake;make`

step 2 and step 3 is necessary.
step 4 is for collecting the log that is sent to slog2.
step 5 is for collecting the log that is sent to syslog.
step 6 is required by WITH_DLT_QNX_SYSTEM.
step 7 is to avoid compile error on test projects.

**Comment by EricMzky** [comment]
> 5\. WITH_DLT_SYSTEM

When I turn on the WITH_DLT_QNX_SYSTEM option, THE following error is reported. If I turn it off, no error is reported.Others have been completely configured as you configured above
![2022-07-12_17-12](https://user-images.githubusercontent.com/37823382/178455310-41e308e4-27a3-49a7-ba99-dcf4f546e33b.png)

**Comment by NeusoftZhangShuang** [comment]
> > 5. WITH_DLT_SYSTEM
> 
> When I turn on the WITH_DLT_QNX_SYSTEM option, THE following error is reported. If I turn it off, no error is reported.Others have been completely configured as you configured above ![2022-07-12_17-12](https://user-images.githubusercontent.com/37823382/178455310-41e308e4-27a3-49a7-ba99-dcf4f546e33b.png)

how did you "turn on" an option? when i tried to turn on an option, i looked for the place where the option is defined, and then change its default value like this:

before:
option(WITH_DLT_SYSTEM "Set to ON to build src/system binaries" **OFF**)
after:
option(WITH_DLT_SYSTEM "Set to ON to build src/system binaries" **ON**)

**Comment by thanhbnq** [comment]
Instead of changing the default values, it must be better if you set the cmake option (as suggestion from pic: Change a value with: cmake -D<Variable>=<Value>)
example: in your makefile, the cmake command could be like this:
`cmake -DWITH_DLT_QNX_SYSTEM=ON  -DDLT_IPC=UNIX_SOCKET  <other options as your target>`

**Comment by EricMzky** [comment]
I'm sorry to bother you again and need your help.We currently need to use V2.17.0 daemon version to compile QNX version, now we have encountered a lot of problems.There will be a lot of errors, what should I do, how to configure the correct CMakelist, thank you!Very troublesome to you!
@thanhbnq @NeusoftZhangShuang

**Comment by EricMzky** [comment]
@thanhbnq thank you ,i will try it
