### ISSUE TITLE
Compile latest version of dlt-daemon on windows 

### ISSUE THREAD

**Issue by Nikhil-V-maker** [COVESA/dlt-daemon#394]
Hi
1. Is there a way to install and use latest version of dlt-receive on windows. 
2. Is there any alternative for windows if dlt-receive can't be used on windows. We want to specify the ports through command line as well.

**Comment by thanhbnq** [comment]
Hello @Nikhil-V-maker ,
1. Basically, dlt-daemon is supporting Linux-based only. There was an attempt from our community in Windows' build, please check more information at https://github.com/COVESA/dlt-daemon/issues/136 
2. Regarding the alternatives for dlt-receive in Windows, you can refer to https://github.com/COVESA/dlt-viewer, an UI-based application for dlt-client side.

**Comment by koreyoshi-wang** [comment]
@Nikhil-V-maker DLT Viewer has a CLI mode, you can you use a project file to specify port!
![image](https://user-images.githubusercontent.com/18671153/181407967-b4b23416-1308-418e-b89e-a91e642f89c4.png)
[project.zip](https://github.com/COVESA/dlt-daemon/files/9204931/project.zip)

**Comment by koreyoshi-wang** [comment]
Found this repository which has pre-compile file for Windows https://github.com/mbehr1/adlt

**Comment by Nikhil-V-maker** [comment]
I compiled the latest version of dlt-daemon
https://github.com/Nikhil-V-maker/dlt-daemon-latest-version-compiled/blob/main/dlt-daemon.zip

Thank you

**Comment by wj-shin** [comment]
NIkhil Thank's for your effort
 but there is some problem in my side
when I run dlt-receive, I cannot execute dlt-receive cygdlt-2.dll 
Do you know some Solution?

**Comment by suiluj** [comment]
@Nikhil-V-maker hi do you have any build instructions for windows?

I would like to build my own version and don't know how to install all needed dependencies.

**Comment by hatran3e** [comment]
> @Nikhil-V-maker hi do you have any build instructions for windows?
> 
> 
> 
> I would like to build my own version and don't know how to install all needed dependencies.

You can start by using Msys or Cygwin as a host to compile this source, dependencies are the same as linux environment.
