### ISSUE TITLE
dlt_client_connect: getaddrinfo: Name or service not known

### ISSUE THREAD

**Issue by Nikhil-V-maker** [COVESA/dlt-daemon#395]
I have compiled latest version of daemon for windows (https://github.com/COVESA/dlt-daemon/issues/136)
and while specifying port information

dlt-receive -a hostname -p port

I am facing this error

`[ 1458.019349]~DLT~   26~ERROR    ~dlt_client_connect: getaddrinfo: Name or service not known`

[dlt-daemon (1).zip](https://github.com/COVESA/dlt-daemon/files/9165626/dlt-daemon.1.zip)

did I miss anything?

**Comment by NeusoftZhangShuang** [comment]
this means dlt-receive can't use "hostname" as a name of a dlt-daemon's address. if your dlt-receive and dlt-daemon are on the same machine, you can try "0.0.0.0", "127.0.0.1", localhost or something else like this to connect to dlt-daemon.

**Comment by thanhbnq** [comment]
Thanks @NeusoftZhangShuang  for your support.

@Nikhil-V-maker I hope you are fine with the answer. I would like to close this and in case you find any unexpected, please raise the new issue.

Thank you all!
