### ISSUE TITLE
Set log level without library?

### ISSUE THREAD

**Issue by krafs** [COVESA/dlt-daemon#404]
Hi,

I'm still learning about DLT, and there's a lot to read through.
I understand that I can read logs from a dlt-daemon by simply connecting to its TCP port. My question -  can I also do other things over TCP, without having to reference the library?

Specifically, I want to set the log level. Do I have to reference the library for this, or can I put together a message and simply send over TCP to port 3490?

**Comment by thanhbnq** [comment]
Hello @krafs ,
Thanks for your question.
Basically, our library is implemented to support all the functionalities related to DLT protocol. 
In case you want to set log level, I think you can use dlt-viewer for your purpose.
Reference here: https://github.com/COVESA/dlt-viewer
