### ISSUE TITLE
Compiling with DLT_QNX_SYSTEM=ON

### ISSUE THREAD

**Issue by ShivaniVerma23** [COVESA/dlt-daemon#413]
Hi,
I am doing message forwarding from slogger2 to DLT. 

I am running below command in directory build to build executable dlt-qnx-system.

cmake .. -DWITH_DLT_QNX_SYSTEM=ON -DWITH_DLT_CXX11_EXT=ON -DCMAKE_CXX_COMPILER=/home/user/qnx710/host/linux/x86_64/usr/bin/qcc

Output: Configuring done
build generating done.

Inside /usr/local/bin : all dlt binaries are created except dlt-qnx-system

**Comment by thanhbnq** [comment]
Hi @ShivaniVerma23 ,

It looks like you are checking your local bin directory which contains the binaries are installed for your local Linux machine (host machine).
If your compilation is successful, you can find out the binary dlt-qnx-system is under your build folder.

Best regards,
Thanh

**Comment by ShivaniVerma23** [comment]
Hi Than,

Thanks for the info.
Actually dlt-qnx-system is not getting generated.

user@BLRTSW00092:~/codebase/QNX_Ethernet/CCSP-2772/sa8295p-hqx-4-2-4-0_hlos_dev_qnx/apps/qnx_ap/dlt-daemon/build/src/dlt-qnx-system$ make
[ 72%] Built target dlt
[ 81%] Building C object src/dlt-qnx-system/CMakeFiles/dlt-qnx-system.dir/dlt-qnx-system.c.o
[ 90%] Building CXX object src/dlt-qnx-system/CMakeFiles/dlt-qnx-system.dir/dlt-qnx-slogger2-adapter.cpp.o
[100%] Linking CXX executable dlt-qnx-system
/home/user/qnx710/host/linux/x86_64/usr/bin/x86_64-pc-nto-qnx7.1.0-ld: cannot find -lrt
/home/user/qnx710/host/linux/x86_64/usr/bin/x86_64-pc-nto-qnx7.1.0-ld: cannot find -lpthread

Can you please suggest how can I change the linking ?

Thanks
Shivani Verma

**Comment by thanhbnq** [comment]
Hello @ShivaniVerma23 ,

I think you should set QNX_HOST and QNX_TARGET environment as well.
Example:

> QNX_TARGET=<path_to>/qnx/qnx-sdp/target/qnx7
> QNX_HOST=<path_to>/qnx/qnx-sdp/host/linux/x86_64

**Comment by thanhbnq** [comment]
More information for QNX, I think you can refer to:
http://www.qnx.com/developers/docs/7.1/#com.qnx.doc.neutrino.prog/topic/devel_OS_version.html

<html><body>


Release | Windows | Linux | Mac
-- | -- | -- | --
QNX SDP 7.0 and more recent | qnxsdp-env.bat | qnxsdp-env.sh | qnxsdp-env.sh


</body>
</html>
