### ISSUE TITLE
IPv6 UDP not working

### ISSUE THREAD

**Issue by phamcongspk** [COVESA/dlt-daemon#419]
I configure DLT daemon using IPv6 and UDP support
(build with WITH_DLT_USE_IPv6=ON and WITH_UDP_CONNECTION=ON)
But it not working with UDP, only TCP is working.
I configure in dlt.conf as follow:
UDPConnectionSetup = 1
UDPMulticastIPAddress = FF14::C
UDPMulticastIPPort = 42557

Am I missing something perhaps?

**Comment by thanhbnq** [comment]
Hello @phamcongspk ,

Sorry for being late here.
I checked with my local Ubuntu setup. IPv6 and UDP is working well.
I'd like to share my configuration.
For dlt.conf:

> UDPConnectionSetup = 1
> UDPMulticastIPAddress = ff02::1
> UDPMulticastIPPort = 3491

And the dltviewer tool, in UDP tab, please choose multicast address as "ff02::/8", port as: 3491 then we can capture dlt message.

Best regards,
Thanh

**Comment by phamcongspk** [comment]
Hi Thanh,

Thanks for your response
I have configured as your suggestion, but it still not working
Below is my setting on dltviewer tool in 2 ways:
![image](https://user-images.githubusercontent.com/116184336/198034362-3fdbb309-27f0-4530-b392-65c31fd141b4.png)

![image](https://user-images.githubusercontent.com/116184336/198034407-db2012ed-713b-4449-ac63-8aea528d614c.png)

Note: I run dltviewer on Window, not Ubuntu
Do I miss something?

Best regards,
Cong.

**Comment by thanhbnq** [comment]
Hi @phamcongspk ,

Well, regarding dlt-viewer for Windows, I can suggest some extra steps you have to perform in this case.

 1.	Check which UDP ports are allowed by firewall. On Windows command line, run:
`netsh firewall show state`

2.	Check which multicast groups Windows can belong to. On Windows command line, run:
`netsh interface ip show joins`

3. (Maybe not necessary) on Ubuntu, Add multicast group of Viewer into ip table by command:
`sudo ip route add <result_of_#2> dev <inet_interface_of_dlt_daemon>`

I hope it could help you.

Best regards,
Thanh

**Comment by phamcongspk** [comment]
Hi Thanh,

Thanks for your help,

Below is the result when I try the step 1 and 2

1. 
![image](https://user-images.githubusercontent.com/116184336/198616348-82577e45-690c-4a73-ad85-32f5e652bb13.png)

2.
![image](https://user-images.githubusercontent.com/116184336/198616664-252f7bfb-c0f5-4b10-b084-c863061cca0c.png)

Base o the result, multicast group  haven't not add on Windows, have it?
What can I do to add the multicast group?

Thank you!
Cong.

**Comment by thanhbnq** [comment]
@phamcongspk 
In the picture 1, it looks like your system is only allowing TCP port 32111.
I think you should contact your admin IT to (maybe) open another UDP port.
I would say I am not an expert in Windows so you'd better consult your IT dept and refer to some following links:
https://learn.microsoft.com/en-us/troubleshoot/windows-server/networking/windows-fireware-rule-block-udp-communication 

In picture 2, it is telling us that the interface 8 Ethernet 2 is already member of some multicast groups.
Hence, you have to guarantee your Ubuntu (host of dlt-daemon) will add one of groups. 
Check my step 3 

Well. If it is somehow difficult to deal with your Windows system, I would suggest to you dltviewer for Ubuntu then :)

Hope it could help you.
Thanh

**Comment by michael-methner** [comment]
I am closing this one. These question is not related to DLT and more like an general IT problem.
