### ISSUE TITLE
[dlt-convert] memory leak vulnerability(dlt_common.c:1521)

### ISSUE THREAD

**Issue by zj3t** [COVESA/dlt-daemon#432]
Hi COVESA Team! 
Contact us to report vulnerabilities. 

## Summary 
I created a crafted DLT file based on the normal DLT file and performed a vulnerability analysis on "dlt-convert"(lastest versioin).

As a result, a memory leak vulnerability existed in "dlt-convert". -> Here, the memory leak is judged not to be disclosure, but to a memory management problem (ex.absence of free() function, etc.).

I rechecked the vulnerability using ASAN (Address Sanitizer).

### Bug Log.
![ASAN_memory_leak](https://user-images.githubusercontent.com/35731091/211467912-c19a9a66-32d5-4f63-9a0e-8b201bf4a33e.png)

**The memory leak code points in the log are**: "https://github.com/COVESA/dlt-daemon/blob/master/src/shared/dlt_common.c:1521"
<img width="894" alt="image" src="https://user-images.githubusercontent.com/35731091/211487184-eb9e7cab-9d59-40b8-827a-970cc8d3af82.png">

The crafted dlt file was converted with the "-m" option to dlt-convert.
-> e.g.) dlt-convert -m "crafted DLT"
[crafted_DLT.zip](https://github.com/COVESA/dlt-daemon/files/10379161/crafted_DLT.zip)

I have a lot of sample files that trigger the vulnerability, so I'll give them to you if you ask.

## Furthermore
[case.zip](https://github.com/COVESA/dlt-daemon/files/10379968/case.zip)

In the case file, the tc_109.dlt file is the file that causes the memory leak.
However, if executed together with the tc_1095/tc_1096.dlt file, a total of 21470 bytes of memory leak occurs.

![case](https://user-images.githubusercontent.com/35731091/211484228-912882de-a21c-4d50-9827-0ff5a423409f.png)

**The memory leak code points in the log are**: "https://github.com/COVESA/dlt-daemon/blob/master/src/shared/dlt_common.c:1439"

<img width="664" alt="image" src="https://user-images.githubusercontent.com/35731091/211485815-2a61ad11-9fa9-47d8-bf09-b2ad294e99d9.png">

### ETC
I will attach one more similar test case. : [etc.zip](https://github.com/COVESA/dlt-daemon/files/10380002/etc.zip)

![case_etc](https://user-images.githubusercontent.com/35731091/211485334-6dedda08-5088-4af5-ab9d-8fd91e5cd523.png)

**With this vulnerability, it was confirmed that Memory Leak can continue to increase.**
![2023-01-10-074232_1920x1080_scrot](https://user-images.githubusercontent.com/35731091/211491397-0515a05b-0912-43e1-bc64-83fb7ed74a74.png)

Please let me know if any information is missing.

Thanks Team :)

**Comment by lvklevankhanh** [comment]
Hello @zj3t ,

Thanks for pointing out. You're right. The dlt_common.c got memory leak vulnerability when we using ASAN (Address Sanitizer).
So, the fixed version will be send for review soon.

KhanhLe

**Comment by zj3t** [comment]
Thanks @lvklevankhanh :)
Can i get the CVE?
I really want it.

**Comment by lvklevankhanh** [comment]
Hello @zj3t , the pull request is under review at https://github.com/COVESA/dlt-daemon/pull/434
Please have a look and leave comments if any.

**Comment by zj3t** [comment]
Hi @lvklevankhanh , 

I have confirmed the pull request.
I admire the quickness of fixing bugs quickly.

Can I request a CVE?

**Comment by michael-methner** [comment]
> Can I request a CVE?

Yes, please go ahead. Thank you for reporting the issue.

**Comment by zj3t** [comment]
Thanks @michael-methner  :)

**Comment by lvklevankhanh** [comment]
The PR https://github.com/COVESA/dlt-daemon/pull/434 is already merged.
