### ISSUE TITLE
About dlt-logd-converter used

### ISSUE THREAD

**Issue by Krocar** [COVESA/dlt-daemon#457]
I try to use DLT-Logd-Converter after the DLT-Daemon running in Android and i has set the LoggingMode = 2. But I can't see anything about logd message in LoggingFile, so I would like to learn about th usage of DLT-Logd-Converter. After looking at the relevant code, I noticed that the content is ultimately written in the DLT_LOG_TS method format. Will this content not be written to the LoggingFile that has already been defined? How can I access the content generated by DLT-Logd-Converter after it has been executed?

**Comment by minminlittleshrimp** [comment]
Hello @Krocar,
Thanks for raising your concern about DLT on Android.
I would like to support you by first making clear some misunderstanding here:
1. dlt.conf is the config file read by dlt-daemon, hence for LoggingMode = 2 and LoggingFilename = <path>, dlt-daemon will buffer internal logs into this path (note that this is internal logs, not logs from android logd)
2. dlt-logd-converter is actually a dlt-user (if you consider the overview [DLT diagram](https://github.com/COVESA/dlt-daemon/blob/master/doc/images/dlt_overview.png)) which makes use of Android API to buffer logs from LogD Android buffer and formats them in dlt log message format, then this so-called dlt-user will make use of dlt user lib (using MACRO DLT_LOG_TS) to buffer formatted dlt logs to dlt-daemon.
3. Now, back to your final question: **_How can I access the content generated by DLT-Logd-Converter after it has been executed?_**
dlt-daemon is holding logs in it ring buffer, you could use dlt-client connecting to other end of dlt-daemon to extract logs: dlt-receive, dlt offline trace feature, dlt offline logstorage, etc. For the easiest case, you could use $ dlt-receive -a <IP/localhost> to get the logs. 

To summerize, you could test dlt-logd-converter by folling these steps:
$ dlt-daemon
$ dlt-logd-converter
$ dlt-receive -a <IP/localhost>

Now you could observe logs from Android native application in dlt format.
Regards,
DLT team

**Comment by Krocar** [comment]
Thank you for addressing my concerns. I have also stored the Android System log using the offline logstorage method. I will try the methods you have provided one by one. 
Lastly, please allow me to express my gratitude to the DLT team. Thank you!
