### ISSUE TITLE
having some problem while saving log context to a file 

### ISSUE THREAD

**Issue by CodeTornato** [COVESA/dlt-daemon#458]
Hey dear dlt team,
I'm new to this dlt community,I have a simple log example program, and I'm trying to save that log context to a file by setting "LoggingMode = 2" in dlt.conf, and yeah a dlt.log file genereted at desired destination,however,the saved file's context was not as desired,
here is my log file
![image](https://user-images.githubusercontent.com/118702310/227412137-55facfec-f721-473f-848c-e9ef8245da21.png)
here is my desired log context to be saved at dlt.log,because that was what I log at main() function.
![image](https://user-images.githubusercontent.com/118702310/227415209-859bd5e4-9648-4a21-9308-5e2e03778012.png)
![image](https://user-images.githubusercontent.com/118702310/227412317-8c40b177-a6a2-4364-8e95-a7dbf257f4ee.png)

and here is my code and dlt.conf
[test_log.zip](https://github.com/COVESA/dlt-daemon/files/11058024/test_log.zip)

so I guess I miss some configuration or anything, please can you help me point out how can I log my log context into file and context will be same as logging it into console?

and also is it able to set the logging output binding in code so I dont have to depend on configuration file like suing dlt_int_file() function, it did'nt work in my code though.
![image](https://user-images.githubusercontent.com/118702310/227418035-e53978a4-f096-43fc-8d91-5f66157deee8.png)

**Comment by minminlittleshrimp** [comment]
Hello @CodeTornato 
To answer your question, could you please refer to this issue: https://github.com/COVESA/dlt-daemon/issues/457
For storing data by files in a specific storage, please look over: https://github.com/COVESA/dlt-daemon/blob/master/doc/dlt_offline_logstorage.md
Thank you so much!

**Comment by CodeTornato** [comment]
thanks so much
