### ISSUE TITLE
Arm compiler 6.6.2 and RTOS

### ISSUE THREAD

**Issue by davidra7** [COVESA/dlt-daemon#492]
Hi,
I am trying to compile the project for RTOS with arm compiler 6.6.2.

My cmake command: 
`cmake .. -DDLT_IPC=UNIX_SOCKET -DWITH_DLT_TESTS=OFF  -DWITH_DLT_USE_IPv6=OFF -DWITH_DLT_EXAMPLES=OFF -DCMAKE_C_COMPILER=/home/david/ARMCompiler6.6.2/bin/armclang  -DCMAKE_CXX_COMPILER=/home/david/ARMCompiler6.6.2/bin/armclang -DCMAKE_BUILD_TYPE=Release`

output:
```
-- The C compiler identification is ARMClang 6.6.201
-- The CXX compiler identification is ARMClang 6.6.201
CMake Error at /usr/share/cmake-3.16/Modules/Compiler/ARMClang.cmake:55 (message):
    System processor 'x86_64' not supported by ARMClang C compiler
    Supported processor: cortex-a5;cortex-a7;cortex-a8;cortex-a9;cortex-a12;cortex-a15;cortex-a17;cortex-a32;cortex-a35;cortex-a53;cortex-a57;cortex-a72;cortex-a73;cortex-m0;cortex-m0plus;cortex-m1;cortex-m3;cortex-m4;cortex-m7;cortex-m23;cortex-m33;cortex-r4;cortex-r4f;cortex-r5;cortex-r7;cortex-r8;cortex-r52;sc000;sc300

Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/Compiler/ARMClang-C.cmake:3 (__compiler_armclang)
  /usr/share/cmake-3.16/Modules/CMakeCInformation.cmake:25 (include)
  CMakeLists.txt:17 (project)
```
Any idea what I am doing wrong? or an advice?

Thanks!
David

**Comment by michael-methner** [comment]
Hello @davidra7 ,
i assume you need to set CMAKE_SYSTEM_PROCESSOR to one of the supported processors.

**Comment by davidra7** [comment]
I added it with cortex-r7 or arm. still the same error.
I think it might be related to cmake support with arm compiler

**Comment by michael-methner** [comment]
Hello  @davidra7 , 
then I cannot help. Sorry.
