### ISSUE TITLE
dlt-deamon says "Unknow Command" when ever i give a dlt.conf file 

### ISSUE THREAD

**Issue by baris-kizilkaya** [COVESA/dlt-daemon#498]
![image](https://github.com/COVESA/dlt-daemon/assets/132439144/75ebb629-1b00-4e56-9469-25ad2ddcd6c3)
![image](https://github.com/COVESA/dlt-daemon/assets/132439144/f938a08b-e14b-40f7-a764-d775da11aef5)

**Comment by baris-kizilkaya** [comment]
and also
![image](https://github.com/COVESA/dlt-daemon/assets/132439144/842a232f-eda1-4982-9435-b856e175c2b6)
![image](https://github.com/COVESA/dlt-daemon/assets/132439144/0c66ea17-f566-4457-b319-6c2666eda61f)

**Comment by lti9hc** [comment]
Hello @baris-kizilkaya,
You have modified dlt.conf with multiple wrong options
Please correct these options and run command again

**Comment by baris-kizilkaya** [comment]
Could you give me a reference of those correct options please.

**Comment by michael-methner** [comment]
Please use our documentation at:
https://github.com/COVESA/dlt-daemon/blob/master/doc/dlt.conf.5.md
or the example at:
https://github.com/COVESA/dlt-daemon/blob/master/src/daemon/dlt.conf
