### ISSUE TITLE
compiling error when using gcc 9.4.0

### ISSUE THREAD

**Issue by woshiyunsk** [COVESA/dlt-daemon#500]
version: 2.18.9
gcc version: 9.4.0
the compiling error information is below:
In function 'strncpy',
    inlined from 'set_ecuid' at /home/yunshuangkun/workspace/dlt-daemon-2.18.9/src/console/dlt-control-common.c:126:17:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:106:10: error: '__builtin_strncpy' specified bound 10 equals destination size [-Werror=stringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));

**Comment by michael-methner** [comment]
This is a duplicate to #485 and was fixed by #499 .
Please use latest upstream version or cherry pick the fix for your build.

**Comment by lvklevankhanh** [comment]
No response from reporter -> closing
