### ISSUE TITLE
CMAKE Error : No CMAKE_CXX_COMPILER could be found

### ISSUE THREAD

**Issue by oblesh6** [COVESA/dlt-daemon#502]
I was following the steps mentioned in the README.md from the https://github.com/COVESA/dlt-daemon page for the Build and Install of DLT.
while executing the cmake .. step, i'm facing the following error.

spx_admin@UbuntuLinux:~/Workspace/github/dlt-daemon-master/build$ cmake ..
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is unknown
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at CMakeLists.txt:17 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!
See also "/home/spx_admin/Workspace/github/dlt-daemon-master/build/CMakeFiles/CMakeOutput.log".
See also "/home/spx_admin/Workspace/github/dlt-daemon-master/build/CMakeFiles/CMakeError.log".

Please provide a solution to solve this.
Thanks.

**Comment by lti9hc** [comment]
Hello @oblesh6 
You are missing C++ compiler
Use "sudo apt-get install build-essential" to install it.

I hope it can help you

**Comment by oblesh6** [comment]
Thank you @lti9hc , it worked :)
