### ISSUE TITLE
User macros log strings with zero term. in conflict to the Autosar specification

### ISSUE THREAD

**Issue by mbehr1** [COVESA/dlt-daemon#512]
The spec (e.g. `PRS_Dlt_00156` and `PRS_Dlt_00373`) says that strings should not be zero terminated but 
e.g. 
https://github.com/COVESA/dlt-daemon/blob/a4ece7602840ae0a048eed7b4a9d8c0bac6a77ec/src/lib/dlt_user.c#L2737

explicitly adds the zero termination to the payload.

Fixing this issue should ensure that strings are just length determined and not zero terminated.

**Comment by LukeTheEngineer** [comment]
Can you highlight where in the Autosar specification the conflict is occurring?

**Comment by LukeTheEngineer** [comment]
> The spec (e.g. `PRS_Dlt_00156` and `PRS_Dlt_00373`) says that strings should not be zero terminated but e.g.
> 
> https://github.com/COVESA/dlt-daemon/blob/a4ece7602840ae0a048eed7b4a9d8c0bac6a77ec/src/lib/dlt_user.c#L2737
> 
> explicitly adds the zero termination to the payload.
> 
> Fixing this issue should ensure that strings are just length determined and not zero terminated.

Can you highlight where in the Autosar specification the conflict is occurring?

**Comment by mbehr1** [comment]
@LukeTheEngineer I pasted the two requirements from the Log and Trace Protocol Specification, AUTOSAR FO R22-11 already above.
PRS_Dlt_00373 describes the encoding for strings and contains:
16 bit length of string
vari info (if set)
data: Data string **without a special terminating item like the NUL- character (\0)**

PRS_Dlt_00156 includes:
At the beginning of the Data Payload, a 16-bit unsigned integer specifies the length of the string (provided in the Data field) in byte.
*Note: The string end is only defined by this length information.*

Is this what you asked for?
(btw: it makes perfect sense. Why send zero termination if the length is already there. And if no client/parser can rely on the zero-term anyhow... (as some encoding might be without)?)

**Comment by LukeTheEngineer** [comment]
@mbehr1 Apologies for the oversight on your previous post. I'll look into it and see if previous contributors added that for a particular reason.

**Comment by LukeTheEngineer** [comment]
@mbehr1 From looking at page 53 of the Autosar FO R22-11 specification, it does indeed layout that the string must not have a null terminator present. However, other contributors added the null terminator to ensure stability. 

`case DLT_RETURN_OK:
    {
        /* Whole string will be copied */
        memcpy(log->buffer + log->size, text, length);
        **The input string might not be null-terminated, so we're doing that by ourselves**
        log->buffer[log->size + length] = '\0';
        log->size += arg_size;
        break;
    }`

Could there be a reason why it cannot have a null terminator that the specification did not state?
To me, it seems the null terminator is harmless and does not raise any critical problems within the Data Payload.

**Comment by LukeTheEngineer** [comment]
@mbehr1 Ah, I see what you are letting on. It does make no sense if we have already determined the length of the string determined. The null terminator doesn't make sense in this context.

**Comment by michael-methner** [comment]
As commented already in #513: I close this bug now as we do not implement DLTv2 protocol as of today. The current implementation is in line with the old spec R20-11.
