### ISSUE TITLE
ringbuffer of dlt-daemon only record the old log messsages

### ISSUE THREAD

**Issue by cumtsmart** [COVESA/dlt-daemon#533]
In my opinion, the ringbuffer of dlt-daemon will record the latest dlt log if no dlt-client connect.  when the buffer is full, the new coming log will squeeze out the oldest one, this's what ringbuffer means. But i found ringbuffer just drop the new coming dlt log when buffer is full.

**Comment by cumtsmart** [comment]
`    if ((sock != DLT_DAEMON_SEND_FORCE) &&
        ((daemon->state == DLT_DAEMON_STATE_BUFFER) || (daemon->state == DLT_DAEMON_STATE_SEND_BUFFER) ||
         (daemon->state == DLT_DAEMON_STATE_BUFFER_FULL))) {
        if (daemon->state != DLT_DAEMON_STATE_BUFFER_FULL) {
            /* Store message in history buffer */
            ret = dlt_buffer_push3(&(daemon->client_ringbuffer), data1, size1, data2, size2, 0, 0);
            if (ret < DLT_RETURN_OK) {
                dlt_daemon_change_state(daemon, DLT_DAEMON_STATE_BUFFER_FULL);
            }
        }
        if (daemon->state == DLT_DAEMON_STATE_BUFFER_FULL) {
            daemon->overflow_counter += 1;
            if (daemon->overflow_counter == 1)
                dlt_vlog(LOG_INFO, "%s: Buffer is full! Messages will be discarded.\n", __func__);

            return DLT_DAEMON_ERROR_BUFFER_FULL;
        }
    } else {
        if ((daemon->overflow_counter > 0) &&
            (daemon_local->client_connections > 0)) {
            sent_message_overflow_cnt++;
            if (sent_message_overflow_cnt >= 2) {
                sent_message_overflow_cnt--;
            }
            else {
                if (dlt_daemon_send_message_overflow(daemon, daemon_local,
                                          verbose) == DLT_DAEMON_ERROR_OK) {
                    dlt_vlog(LOG_WARNING,
                             "%s: %u messages discarded! Now able to send messages to the client.\n",
                             __func__,
                             daemon->overflow_counter);
                    daemon->overflow_counter = 0;
                    sent_message_overflow_cnt--;
                }
            }
        }
    }`

**Comment by cumtsmart** [comment]
`        if (daemon->state != DLT_DAEMON_STATE_BUFFER_FULL) {
            /* Store message in history buffer */
            ret = dlt_buffer_push3(&(daemon->client_ringbuffer), data1, size1, data2, size2, 0, 0);
            if (ret < DLT_RETURN_OK) {
                dlt_daemon_change_state(daemon, DLT_DAEMON_STATE_BUFFER_FULL);
            }
        }
        if (daemon->state == DLT_DAEMON_STATE_BUFFER_FULL) {
            daemon->overflow_counter += 1;
            if (daemon->overflow_counter == 1)
                dlt_vlog(LOG_INFO, "%s: Buffer is full! Messages will be discarded.\n", __func__);

            return DLT_DAEMON_ERROR_BUFFER_FULL;
        }
    } else {
        if ((daemon->overflow_counter > 0) &&
            (daemon_local->client_connections > 0)) {
            sent_message_overflow_cnt++;
            if (sent_message_overflow_cnt >= 2) {
                sent_message_overflow_cnt--;
            }
            else {
                if (dlt_daemon_send_message_overflow(daemon, daemon_local,
                                          verbose) == DLT_DAEMON_ERROR_OK) {
                    dlt_vlog(LOG_WARNING,
                             "%s: %u messages discarded! Now able to send messages to the client.\n",
                             __func__,
                             daemon->overflow_counter);
                    daemon->overflow_counter = 0;
                    sent_message_overflow_cnt--;
                }
            }
        }
    }`

**Comment by cumtsmart** [comment]
Logic is in dlt_daemon_client.c:

    if ((sock != DLT_DAEMON_SEND_FORCE) &&
        ((daemon->state == DLT_DAEMON_STATE_BUFFER) || (daemon->state == DLT_DAEMON_STATE_SEND_BUFFER) ||
         (daemon->state == DLT_DAEMON_STATE_BUFFER_FULL))) {
        if (daemon->state != DLT_DAEMON_STATE_BUFFER_FULL) {
            /* Store message in history buffer */
            ret = dlt_buffer_push3(&(daemon->client_ringbuffer), data1, size1, data2, size2, 0, 0);
            if (ret < DLT_RETURN_OK) {
                dlt_daemon_change_state(daemon, DLT_DAEMON_STATE_BUFFER_FULL);
            }
        }
        if (daemon->state == DLT_DAEMON_STATE_BUFFER_FULL) {
            daemon->overflow_counter += 1;
            if (daemon->overflow_counter == 1)
                dlt_vlog(LOG_INFO, "%s: Buffer is full! Messages will be discarded.\n", __func__);

            return DLT_DAEMON_ERROR_BUFFER_FULL;
        }
    } else {
        if ((daemon->overflow_counter > 0) &&
            (daemon_local->client_connections > 0)) {
            sent_message_overflow_cnt++;
            if (sent_message_overflow_cnt >= 2) {
                sent_message_overflow_cnt--;
            }
            else {
                if (dlt_daemon_send_message_overflow(daemon, daemon_local,
                                          verbose) == DLT_DAEMON_ERROR_OK) {
                    **dlt_vlog(LOG_WARNING,
                             "%s: %u messages discarded! Now able to send messages to the client.\n",
                             __func__,**
                             daemon->overflow_counter);
                    daemon->overflow_counter = 0;
                    sent_message_overflow_cnt--;
                }
            }
        }
    }

**Comment by minminlittleshrimp** [comment]
Hello @cumtsmart ,
thanks for your interest in DLT ring buffer.

I would like to briefly go through some explanation about DLT daemon ring buffer and code logic in dlt-daemon-client-send:
DLT daemon will switch to buffer full state after reaching max ring buffer size. The log info about discarded messages actually about the old messages.
```
[20350.638744]~DLT~29161~DEBUG    ~BufferLength=424, HeaderSize=42, DataSize=20
[20350.638746]~DLT~29161~DEBUG    ~BufferLength=370, HeaderSize=42, DataSize=20
[20350.638749]~DLT~29161~DEBUG    ~BufferLength=316, HeaderSize=42, DataSize=20
[20350.638751]~DLT~29161~DEBUG    ~BufferLength=262, HeaderSize=42, DataSize=20
[20350.638754]~DLT~29161~DEBUG    ~BufferLength=208, HeaderSize=42, DataSize=20
[20350.638756]~DLT~29161~DEBUG    ~BufferLength=154, HeaderSize=42, DataSize=20
[20350.638759]~DLT~29161~DEBUG    ~BufferLength=100, HeaderSize=42, DataSize=20
[20350.638762]~DLT~29161~DEBUG    ~BufferLength=46, HeaderSize=42, DataSize=20
[20350.645873]~DLT~29161~DEBUG    ~BufferLength=46, HeaderSize=42, DataSize=20
[20351.147585]~DLT~29161~DEBUG    ~BufferLength=46, HeaderSize=42, DataSize=20
[20351.651632]~DLT~29161~DEBUG    ~BufferLength=46, HeaderSize=42, DataSize=20
[20352.152892]~DLT~29161~DEBUG    ~BufferLength=46, HeaderSize=42, DataSize=20
[20352.152896]~DLT~29161~INFO     ~Switched to buffer full state.
[20352.152897]~DLT~29161~INFO     ~dlt_daemon_client_send: Buffer is full! Messages will be discarded.
[20352.653984]~DLT~29161~DEBUG    ~BufferLength=46, HeaderSize=42, DataSize=20
[20352.740147]~DLT~29161~INFO     ~dlt_daemon_send_ringbuffer_to_client()
[20352.740152]~DLT~29161~DEBUG    ~Can't send contents of ring buffer to clients
[20353.154545]~DLT~29161~DEBUG    ~BufferLength=46, HeaderSize=42, DataSize=20
[20353.655243]~DLT~29161~DEBUG    ~BufferLength=46, HeaderSize=42, DataSize=20
[20353.740418]~DLT~29161~INFO     ~dlt_daemon_send_ringbuffer_to_client()
[20353.740424]~DLT~29161~DEBUG    ~Can't send contents of ring buffer to clients
[20354.159856]~DLT~29161~DEBUG    ~BufferLength=46, HeaderSize=42, DataSize=20
[20354.660597]~DLT~29161~DEBUG    ~BufferLength=46, HeaderSize=42, DataSize=20
[20354.739157]~DLT~29161~INFO     ~dlt_daemon_send_ringbuffer_to_client()
[20354.739162]~DLT~29161~DEBUG    ~Can't send contents of ring buffer to clients
[20355.164794]~DLT~29161~DEBUG    ~BufferLength=46, HeaderSize=42, DataSize=20
[20355.665764]~DLT~29161~DEBUG    ~BufferLength=46, HeaderSize=42, DataSize=20
```
I agree that the log message here is not clear, maybe "Discard old messages" would be better.
How to check:
```
$ dlt-daemon &
$ dlt-test-stress-user -n 10000 -r 100 &
```
Wait for a couple of minutes and receive logs:
```
$ dlt-receive -a localhost
```

**Comment by cumtsmart** [comment]
@minminlittleshrimp 
Thanks for your reply.   
But in my test, it's not "Discard old messages".  Ringbuffer just drop the new coming dlt log when buffer is full.
For example:
set RingbufferMaxSize = 10000, and there is no dlt client connected, the dlt log will store in Ringbuffer.  When the Ringbuffer is full(>= RingbufferMaxSize), new coming dlt log will be discard.

`208754 2023/09/04 09:57:03.289072 2140.1343 253 ECU1 SYS Macc 8773 log warn verbose 1 W MD.LCM.MsgHandler Get a LCMexecCmd ID=60010 From=102
208755 2023/09/04 09:57:03.289076 2140.1344 243 ECU1 SYS McuM 8773 log info verbose 1 Get REPLY command
208756 2023/09/04 09:57:03.289080 2140.1345 244 ECU1 SYS McuM 8773 log warn verbose 1 Receive a reply not in wait queue! type:102 id:60010
208757 2023/09/04 09:57:03.289084 2140.1346 254 ECU1 SYS Macc 8773 log info verbose 1 N MD.LCM.LifeCycle toggle:Nominal
208758 2023/09/04 09:57:03.289088 2140.1789 55 ECU1 RCM RM 2256 log info verbose 1 [RADIO][AMFM_APP] AFQUAL: current station quality is : 10, Reception lvl: 1,0
208759 2023/09/04 09:57:03.289092 2140.2064 250 ECU1 AFST Macc 8768 log info verbose 1 N MD.positioning.PositioningManager packet:<=== {"frametype":"6","flag":"ok","timestamp":"1693791459497","latitude":"31.974615","longitude":"118.75669500000001","heading":"0","drstatus":"1","quality":"10","fixType":"3"}
208760 2023/09/04 09:57:03.289103 2140.2078 255 ECU1 SYS Macc 8773 log info verbose 1 N MD.positioning.PositioningManager packet:<=== {"frametype":"6","flag":"ok","timestamp":"1693791459497","latitude":"31.974615","longitude":"118.75669500000001","heading":"0","drstatus":"1","quality":"10","fixType":"3"}
208761 2023/09/04 09:57:03.289108 3300.8906 0 ECU1 DA1 DC1 0 control response non-verbose 0 [message_buffer_overflow ok] 01 22 4e 03 00
208762 2023/09/04 09:57:03.314950 3300.8924 79 ECU1 AFST Macc 8768 log info verbose 1 N MD.LCM.EarlyInitService LCM ProcessEventQueue:17 ~2693059664
208763 2023/09/04 09:57:03.314985 3300.8924 80 ECU1 AFST Macc 8768 log info verbose 1 N MD.LCM.EarlyInitService notifyUniqueEvent 0:2
208764 2023/09/04 09:57:03.314991 3300.8925 81 ECU1 AFST Macc 8768 log info verbose 1 N MD.LCM.EarlyInitService LCM ProcessEventQueue:17 Complete ~2693059664
208765 2023/09/04 09:57:03.314996 3300.9161 228 ECU1 SYS Macc 8773 log warn verbose 1 W MD.DataStore syncDID :0xd404 value:FF 13 , no change`

**Comment by minminlittleshrimp** [comment]
Hello @cumtsmart 

We need to differentiate between dlt ring buffer and libdlt buffer.
If dlt-daemon is not available, new messages will be discarded at libdlt buffer.
Hence, dlt-daemon must be available for message overwriting.
Honestly, this is our mechanism for dlt, so please try again with dlt-daemon avaiable on host.

Regards

**Comment by cumtsmart** [comment]
@minminlittleshrimp 

I mean the ringbuffer on dlt-daemon size, not libdlt buffer.  And my dlt-daemon is also started up.

My attention is focused on **dlt_daemon_client.c::dlt_daemon_client_send**.  In this function, will invoke
    /* Store message in history buffer */
    ret = dlt_buffer_push3(&(daemon->client_ringbuffer), data1, (unsigned int) size1, data2, (unsigned int) size2, 0, 0);

**dlt_buffer_push3** method store dlt message in dlt-daemon's proccess ringbuffer.

when a dlt-client connected, dlt message in dlt-daemon's proccess ringbuffer will sync to dlt-client.

Is my understanding correct？

**Comment by minminlittleshrimp** [comment]
I just check again in the source code.
Basically I could see both libdlt and dlt-daemon using the same API for buffering.
Also I tested following your report, in fact the new logs are discarded:
```
$ dlt-test-stress-user -n 10000 -d 10 -r 1
Tests starting
Tests finished

$ dlt-receive -a localhost
2023/09/07 17:18:05.980989  179710580 060 ECU1 DIFT INFO log info V 2 [61 00'01'02'03'04'05'06'07'08'09'0a'0b'0c'0d'0e'0f'10'11'12'13'14'15'16'17'18'19'1a'1b'1c'1d'1e'1f'20'21'22'23'24'25'26'27'28'29'2a'2b'2c'2d'2e'2f'30'31'32'33'34'35'36'37'38'39'3a'3b'3c'3d'3e'3f'40'41'42'43'44'45'46'47'48'49'4a'4b'4c'4d'4e'4f'50'51'52'53'54'55'56'57'58'59'5a'5b'5c'5d'5e'5f'60'61'62'63]
2023/09/07 17:18:05.980997  179710581 061 ECU1 DIFT INFO log info V 2 [62 00'01'02'03'04'05'06'07'08'09'0a'0b'0c'0d'0e'0f'10'11'12'13'14'15'16'17'18'19'1a'1b'1c'1d'1e'1f'20'21'22'23'24'25'26'27'28'29'2a'2b'2c'2d'2e'2f'30'31'32'33'34'35'36'37'38'39'3a'3b'3c'3d'3e'3f'40'41'42'43'44'45'46'47'48'49'4a'4b'4c'4d'4e'4f'50'51'52'53'54'55'56'57'58'59'5a'5b'5c'5d'5e'5f'60'61'62'63]
2023/09/07 17:18:05.981006  179761457 000 ECU1 DA1- DC1- control response N 1 [message_buffer_overflow, ok, 01 d6 26 00 00]
```
I could say whenever this control response log appears to indicate the overflow: message_buffer_overflow, no new logs are buffered. Let me take a deeper understanding of this behavior. If this is true, it is no more called ring buffer but just a normal buffer.

Regards

**Comment by minminlittleshrimp** [comment]
Hello @cumtsmart 

I observed in the source code and by doing some tests with continuously increasing the buffer.
What I have found is that this ring buffer is designed to use as producer/consumer mode (write faster than read, and in fact in this case read = 0 till buffer full):
https://github.com/COVESA/dlt-daemon/blob/4ed1b974f6155f8a042b4b39a2619898981e3870/src/shared/dlt_common.c#L2627
https://github.com/COVESA/dlt-daemon/blob/4ed1b974f6155f8a042b4b39a2619898981e3870/src/shared/dlt_common.c#L2634
,in which it means the lost of recent logs. No overwriting process there but only a checking for full buffer during while loop of writing:
https://github.com/COVESA/dlt-daemon/blob/4ed1b974f6155f8a042b4b39a2619898981e3870/src/shared/dlt_common.c#L2607

Hence, the mechanism of dlt ring buffers:
+ Both dlt-daemon and libdlt are using their own ring buffers.
+ Ring buffers in dlt-daemon and libdlt are all producer/consumer mode -> new logs will be discarded.

In a nutshell, we need to correct the document instead  😀 

Hello @michael-methner , please kindly check my points.
Thank you in advance.

**Comment by minminlittleshrimp** [comment]
In fact, we do not need to correct the doc:
https://github.com/COVESA/dlt-daemon/blob/master/doc/dlt_design_specification.md#overflow-handling

,,If the named pipe/socket of the DLT daemon is full, an overflow flag is set and the message stored in a ring buffer. The next time, a message could be sent to the DLT daemon, an overflow message is sent first, then the contents of the ring buffer. If sending of this message was possible, the overflow flag is reset.''

No overwriting behavior mention, only store old messages.

**Comment by cumtsmart** [comment]
@minminlittleshrimp
Ok, thanks for your time.😀

**Comment by michael-methner** [comment]
not a bug
