### ISSUE TITLE
Not  offline logstoreage to new file in continuous power on

### ISSUE THREAD

**Issue by tangzhiqiang3** [COVESA/dlt-daemon#540]
When a log file is full, no new files can be created to write logs; 
![image](https://github.com/COVESA/dlt-daemon/assets/56831849/bdc34843-88d4-41bd-b197-5336f35bd2f4)

**Comment by minminlittleshrimp** [comment]
Hello @tangzhiqiang3 ,
thank you so much for your interest in DLT topics.

Regarding this topic, I would rather say that this is DLT designed mechanism. Please kindly read through this discussion: https://github.com/COVESA/dlt-daemon/issues/533

In case you still want to discuss further, please kindly raise your point here, and we are open to support you.

DLT team

**Comment by tangzhiqiang3** [comment]
version: origin/master(4ed1b974f6155f8a042b4b39a2619898981e3870) branch.

dlt.conf
```
##############################################################################
# Offline logstorage                                                         #
##############################################################################
# Send automatic get log info response during context registration
SendContextRegistration = 1

# Set ECU ID (Default: ECU1)
ECUId = CSC1

# Size of shared memory (Default: 100000)
SharedMemorySize = 100000

# Directory where to store the persistant configuration (Default: /tmp)
PersistanceStoragePath = /var/data

# Store DLT log messages, if not set offline logstorage is off (Default: off)
# Maximum devices to be used as offline logstorage devices
OfflineLogstorageMaxDevices = 10

# Path to store DLT offline log storage messages (Default: off)
OfflineLogstorageDirPath = /var/log/qisi

# Wrap around value for log file count in file name (Default: UINT_MAX)
OfflineLogstorageMaxCounter = 100

# Maximal used memory for Logstorage Cache in KB (Default: 30000 KB)
OfflineLogstorageCacheSize = 80000

# Store DLT messages to local directory, if not set offline Trace is off (Default: off)
OfflineTraceDirectory = /var/log/qisi

ControlSocketPath = /tmp/tmp.xxxx.sock

```

dlt_logstorage.conf
```
[FILTER1]
LogAppName=xxx
ContextName=xxx, xxx
LogLevel=DLT_LOG_INFO
File=xxx
FileSize=10485760
NOFiles=50
GzipCompression=on
```
Could you please help me take a look? Thank you

**Comment by minminlittleshrimp** [comment]
Hello @tangzhiqiang3 
so sorry we are busy these days.

Do you have any progress in this issue?
I will try to reproduce on my side and comment.

Regards

**Comment by minminlittleshrimp** [comment]
Issue has not been fixed yet, please keep this open

**Comment by minminlittleshrimp** [comment]
Hello @tangzhiqiang3 
Sorry for my late fixing.
Fix is now available for review at: #571

**Comment by tangzhiqiang3** [comment]
Okay, I'll try again

**Comment by minminlittleshrimp** [comment]
Please kindly try and ping me if there are any issues
Thank you
