### ISSUE TITLE
Stack Smashing Error : QNX 

### ISSUE THREAD

**Issue by aazaad29** [COVESA/dlt-daemon#541]
When I run the compiled CPP code for QNX platform .....it throws Stack Smashing Error .*** stack smashing detected ***: - terminated Abort (core dumped)  after the function call after sending logs which I am able to view in the DLT-Viewer. Can someone share their sample QNX c++ Code for reference  ....??I am not able to figure out the issue  .....why the  C++ app is crashing after sending logs ??

```
#include <iostream>

using namespace std;


#include <stdio.h>

#include <dlt/dlt.h>

// Define a DLT context

DLT_DECLARE_CONTEXT(ctx);


// Function that logs a message using the provided DLT context

void logMessageWithDLT() 
{

    // Log a message using the provided DLT context
    DLT_LOG(ctx, DLT_LOG_ERROR, DLT_CSTRING("Inside logMessageWithDLT: Logging a message "))

}

int main()

{

  std::cout <<"THOR LOVE AND THUNDER ";

  DLT_REGISTER_APP("MOCK", "Test Application for Logging");

  DLT_REGISTER_CONTEXT(ctx,"MC1","My hello Context 1");

 
 // Register the context


    DLT_LOG(ctx, DLT_LOG_INFO, DLT_CSTRING("HELLO WORLD "));


    // Call the function

    logMessageWithDLT();

**// APP crashes here** 


        DLT_UNREGISTER_CONTEXT(ctx);
        DLT_UNREGISTER_APP();

**Comment by aazaad29** [comment]
@minminlittleshrimp any updates on this issue ?? I am not able to use DLT logging in QNX environment inside function calls as it throws stack smashing error ...

**Comment by michael-methner** [comment]
Hello @aazaad29 ,
this is a duplicate to #536 . Please avoid creating multiple issues for the same problem.
