### ISSUE TITLE
How to Use FIFO(IPC meachanism) on QNX

### ISSUE THREAD

**Issue by Vishalwagh05** [COVESA/dlt-daemon#555]
Hello Team,

I want to install dlt-daemon with FIFO on QNX, so how to do it? which flags has to set in cmakelists while cross compiling dlt on linux? what permissions are needed for FIFO file because currently after running dlt-daemon binary on QNX then I faced this issue:

DLT~1351740~WARNING  ~FIFO user /var/dlt cannot be opened (Operation not permitted)!
DLT~1351740~ERROR    ~Unable to initialize fifo.
DLT~1351740~CRITICAL ~Initialization of local connections failed!

How to resolve this?

**Comment by minminlittleshrimp** [comment]
Hello @Vishalwagh05 

I afraid this issue from yours is actually out of our scope.
There are some reasons:
+ QNX is now provided close-source.
+ Depending on your project, target, chipset
+ Specific permission provided to you, obviously there is a message (not permitted)

Regards

**Comment by Vishalwagh05** [comment]
Okay thank you @minminlittleshrimp

**Comment by Vishalwagh05** [comment]
@minminlittleshrimp Actually issue is with security policies of QNX so after changing those policies now I am able to run dlt-daemon on QNX...

but now when I just running simple DLT_Daemon code on QNX then I faced this issue:

[ 1196.742587]~DLT~1294395~NOTICE   ~[dlt_free] data is still readable... [14] bytes read

so @minminlittleshrimp you have any idea about it then please suggest me....

**Comment by minminlittleshrimp** [comment]
Hello @Vishalwagh05 
I believe this is not related to FIFO QNX.
It points out there are readable bytes when trying to free using UNIX_SOCKET:
https://github.com/COVESA/dlt-daemon/blob/f74e548ba3b7cf989d4b80bcb918f31840d980ae/src/lib/dlt_user.c#L1095

**Comment by Vishalwagh05** [comment]
Hello @minminlittleshrimp, Yes it is not related to FIFO QNX.
I am just running simple dlt-daemon code on QNX, where I faced this issue.
Any solution for that?

**Comment by minminlittleshrimp** [comment]
Hello,
it is not clear to me about dlt code, is it an App you build that using libdlt?

**Comment by Vishalwagh05** [comment]
Hello @minminlittleshrimp , Yes I build this with libdlt.

**Comment by minminlittleshrimp** [comment]
I do not think this is an issue, since the setting up and testing on our side.
I would suggest a briefly reading through developer's doc: https://github.com/COVESA/dlt-daemon/blob/master/doc/dlt_for_developers.md
There are things to avoid when you are trying to perform a logging on QNX with DLT.
Regards
