### ISSUE TITLE
how to compile this project with ndk?

### ISSUE THREAD

**Issue by guitLearn** [COVESA/dlt-daemon#556]
I use ndk compile this project. It occured sockets.h can't find. 
cmake  -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-31 -DANDROID_NDK=/opt/android-ndk-r25c -DCMAKE_TOOLCHAIN_FILE=/opt/android-ndk-r25c/build/cmake/android.toolchain.cmake  -DCMAKE_INSTALL_PREFIX=./install   .. && make -j4
CMake Deprecation Warning at CMakeLists.txt:17 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- The C compiler identification is Clang 14.0.7
-- The CXX compiler identification is Clang 14.0.7
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /opt/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/android-ndk-r25c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build type not defined. Using default build type 'RelWithDebInfo'.
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Looking for include file arpa/inet.h
-- Looking for include file arpa/inet.h - found
-- Looking for include file fcntl.h
-- Looking for include file fcntl.h - found
-- Looking for include file float.h
-- Looking for include file float.h - found
-- Looking for include file limits.h
-- Looking for include file limits.h - found
-- Looking for include file netdb.h
-- Looking for include file netdb.h - found
-- Looking for include file netinet/in.h
-- Looking for include file netinet/in.h - found
-- Looking for include file stddef.h
-- Looking for include file stddef.h - found
-- Looking for include file stdint.h
-- Looking for include file stdint.h - found
-- Looking for include file stdlib.h
-- Looking for include file stdlib.h - found
-- Looking for include file string.h
-- Looking for include file string.h - found
-- Looking for include file sys/ioctl.h
-- Looking for include file sys/ioctl.h - found
-- Looking for include file sys/socket.h
-- Looking for include file sys/socket.h - found
-- Looking for include file sys/time.h
-- Looking for include file sys/time.h - found
-- Looking for include file unistd.h
-- Looking for include file unistd.h - found
-- Looking for include file sys/ipc.h
-- Looking for include file sys/ipc.h - found
-- Looking for include file ctype.h
-- Looking for include file ctype.h - found
-- Looking for include file signal.h
-- Looking for include file signal.h - found
-- Looking for include file syslog.h
-- Looking for include file syslog.h - found
-- Looking for include file sys/stat.h
-- Looking for include file sys/stat.h - found
-- Looking for include file linux/stat.h
-- Looking for include file linux/stat.h - found
-- Looking for include file sys/uio.h
-- Looking for include file sys/uio.h - found
-- Looking for include file termios.h
-- Looking for include file termios.h - found
-- Looking for include file mqueue.h
-- Looking for include file mqueue.h - not found
-- Looking for clock_gettime
-- Looking for clock_gettime - found
-- Looking for floor
-- Looking for floor - found
-- Looking for fork
-- Looking for fork - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for gettimeofday
-- Looking for gettimeofday - found
-- Looking for inet_ntoa
-- Looking for inet_ntoa - found
-- Looking for malloc
-- Looking for malloc - found
-- Looking for memmove
-- Looking for memmove - found
-- Looking for memset
-- Looking for memset - found
-- Looking for mkfifo
-- Looking for mkfifo - found
-- Looking for select
-- Looking for select - found
-- Looking for socket
-- Looking for socket - found
-- Looking for strchr
-- Looking for strchr - found
-- Looking for strerror
-- Looking for strerror - found
-- Looking for strstr
-- Looking for strstr - found
-- Looking for strtol
-- Looking for strtol - found
-- Looking for mq_open
-- Looking for mq_open - not found
-- Looking for mq_close
-- Looking for mq_close - not found
-- Looking for mq_unlink
-- Looking for mq_unlink - not found
-- Looking for mq_send
-- Looking for mq_send - not found
-- Looking for mq_receive
-- Looking for mq_receive - not found
-- Looking for pthread_setname_np in -pthread
-- Looking for pthread_setname_np in -pthread - found
-- Disable network trace interface since message queue is not supported
-- Using pthread_setname_np API to set thread name
-- 
-- -------------------------------------------------------------------------------
-- Build for Version 2.18.10 build v2.18.10_12_gf74e548 version state STABLE
-- WITH_SYSTEMD = OFF
-- WITH_SYSTEMD_WATCHDOG = OFF
-- WITH_SYSTEMD_JOURNAL = OFF
-- WITH_DOC = OFF
-- WITH_MAN = OFF
-- WITH_DLT_ADAPTOR = OFF
-- WITH_DLT_ADAPTOR_UDP = OFF
-- WITH_DLT_CONSOLE = ON
-- WITH_DLT_CONSOLE_WO_CTRL = OFF
-- WITH_DLT_CONSOLE_WO_SBTM = OFF
-- WITH_DLT_EXAMPLES = ON
-- WITH_DLT_SYSTEM = OFF
-- WITH_DLT_FILETRANSFER = OFF
-- WITH_DLT_DBUS = OFF
-- WITH_DLT_TESTS = ON
-- WITH_DLT_UNIT_TESTS = OFF
-- WITH_DLT_COVERAGE = OFF
-- WITH_DLT_SHM_ENABLE = OFF
-- WITH_DLTTEST = OFF
-- BUILD_GMOCK = OFF
-- WITH_GIT_SUBMODULE = OFF
-- WITH_DLT_PKGCONFIG = ON
-- WITH_DLT_CXX11_EXT = OFF
-- WITH_DLT_COREDUMPHANDLER = OFF
-- WITH_DLT_KPI = OFF
-- WITH_DLT_FATAL_LOG_TRAP = OFF
-- WITH_CHECK_CONFIG_FILE = OFF
-- WITH_TESTSCRIPTS = OFF
-- WITH_GPROF = OFF
-- WITH_DLT_USE_IPv6 = ON
-- DLT_USER = covesa
-- BUILD_SHARED_LIBS = ON
-- TARGET_CPU_NAME = 
-- CMAKE_INSTALL_PREFIX = /opt/TDA4X/TauristarPlatformThirdparty/third_party/dlt-daemon/buildAndroid/install
-- CMAKE_BUILD_TYPE = RelWithDebInfo
-- CMAKE_HOST_SYSTEM_PROCESSOR = x86_64
-- CMAKE_SYSTEM_PROCESSOR = aarch64
-- WITH_DLT_LOGSTORAGE_CTRL_UDEV = OFF
-- WITH_DLT_LOGSTORAGE_GZIP = OFF
-- DLT_IPC = FIFO(Path: /tmp)
-- WITH_DLT_DAEMON_VSOCK_IPC = OFF
-- WITH_DLT_LIB_VSOCK_IPC = OFF
-- DLT_VSOCK_PORT = 13490
-- WITH_UDP_CONNECTION = OFF
-- WITH_DLT_QNX_SYSTEM = OFF
-- WITH_DLT_NETWORK_TRACE = ON
-- WITH_LIB_NO_VERSION = 
-- WITH_LIB_SHORT_VERSION = OFF
-- WITH_LEGACY_INCLUDE_PATH = ON
-- WITH_EXTENDED_FILTERING = OFF
-- WITH_DLT_DISABLE_MACRO = OFF
-- WITH_DLT_FILE_LOGGING_SYSLOG_FALLBACK = OFF
-- WITH_DLT_LOG_LEVEL_APP_CONFIG = OFF
-- Change a value with: cmake -D<Variable>=<Value>
-- -------------------------------------------------------------------------------
-- 
-- Configuring done (3.0s)
-- Generating done (0.1s)
-- Build files have been written to: /opt/TDA4X/TauristarPlatformThirdparty/third_party/dlt-daemon/buildAndroid
[  1%] Building C object src/lib/CMakeFiles/dlt.dir/dlt_user.c.o
[  2%] Building C object src/lib/CMakeFiles/dlt.dir/dlt_client.c.o
[  3%] Building C object src/lib/CMakeFiles/dlt.dir/dlt_filetransfer.c.o
[  5%] Building C object src/daemon/CMakeFiles/dlt-daemon.dir/dlt-daemon.c.o
[  6%] Building C object src/lib/CMakeFiles/dlt.dir/dlt_env_ll.c.o
[  7%] Building C object src/lib/CMakeFiles/dlt.dir/__/shared/dlt_common.c.o
[  8%] Building C object src/lib/CMakeFiles/dlt.dir/__/shared/dlt_multiple_files.c.o
[ 10%] Building C object src/lib/CMakeFiles/dlt.dir/__/shared/dlt_protocol.c.o
[ 11%] Building C object src/lib/CMakeFiles/dlt.dir/__/shared/dlt_user_shared.c.o
[ 12%] Building C object src/daemon/CMakeFiles/dlt-daemon.dir/dlt_daemon_client.c.o
[ 14%] Building C object src/daemon/CMakeFiles/dlt-daemon.dir/dlt_daemon_common.c.o
[ 15%] Building C object src/daemon/CMakeFiles/dlt-daemon.dir/dlt_daemon_connection.c.o
[ 16%] Building C object src/daemon/CMakeFiles/dlt-daemon.dir/dlt_daemon_event_handler.c.o
[ 17%] Building C object src/daemon/CMakeFiles/dlt-daemon.dir/dlt_daemon_offline_logstorage.c.o
[ 19%] Building C object src/daemon/CMakeFiles/dlt-daemon.dir/dlt_daemon_serial.c.o
[ 20%] Building C object src/daemon/CMakeFiles/dlt-daemon.dir/dlt_daemon_socket.c.o
[ 21%] Building C object src/daemon/CMakeFiles/dlt-daemon.dir/dlt_daemon_unix_socket.c.o
/opt/TDA4X/TauristarPlatformThirdparty/third_party/dlt-daemon/src/daemon/dlt_daemon_unix_socket.c:32:13: fatal error: 'cutils/sockets.h' file not found
#   include <cutils/sockets.h> /* for android_get_control_socket() */
            ^~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [src/daemon/CMakeFiles/dlt-daemon.dir/build.make:188: src/daemon/CMakeFiles/dlt-daemon.dir/dlt_daemon_unix_socket.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 23%] Linking C shared library libdlt.so
ld: error: unable to find library -lsocket
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/lib/CMakeFiles/dlt.dir/build.make:209: src/lib/libdlt.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:345: src/lib/CMakeFiles/dlt.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:371: src/daemon/CMakeFiles/dlt-daemon.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by minminlittleshrimp** [comment]
Hello @guitLearn 
thanks for your interest in DLT.

I am not an expert in Android Compilation. As far as I know, dlt is designed under the scope of Soong build, I mean we use Android.bp file for that. And I also have not been aware of Dlt compilation supporting ndk build.

Regards
