### ISSUE TITLE
dlt-daemon 2.18.10 the gzip log file is empty.

### ISSUE THREAD

**Issue by WouldCome** [COVESA/dlt-daemon#585]
my dlt_logstorage_conf configuration is shown in dlt_logstorage_conf.png.
The error log is shown in dlt_error_log.png.
The change is shown in the fix.png(right side of the picture), fixes the empty gzip log file.
The main reason is that when the GzipCompression parameter is on, the dlt_logstorage_prepare_on_msg function only determines config->log, which causes the dlt_logstorage_write_to_log function to return an error before writing to the log.
![dlt_error_log](https://github.com/COVESA/dlt-daemon/assets/153883428/22fad09d-1a63-4330-9e2b-04c0747f6abe)
![dlt_logstorage_conf](https://github.com/COVESA/dlt-daemon/assets/153883428/34d25db0-f0aa-47dc-b622-5d21a7706ca4)
![fix](https://github.com/COVESA/dlt-daemon/assets/153883428/875df784-eb5e-4873-8531-43cf2b907754)

**Comment by minminlittleshrimp** [comment]
Hello @WouldCome 
Thank you so much for your report.

Could you please kindly try this fix: https://github.com/COVESA/dlt-daemon/commit/543087ba98c103dc576edadeccf614c9dab1b9b3?
I think your issue could be fixed with this.

Regards

**Comment by WouldCome** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by WouldCome** [comment]
Ok, I'll try it tomorrow and get back to you as soon as possible.

**Comment by WouldCome** [comment]
Thanks for your help, I have verified that the issue has indeed been fixed.

Best regards

**Comment by minminlittleshrimp** [comment]
That's great.
Hence close the issue.
Thank you!

**Comment by WouldCome** [comment]
Although the gzip logfile is no longer empty, the dlt logfile shows the following error.
Please also take a look, thank a lot.
![image](https://github.com/COVESA/dlt-daemon/assets/153883428/31d51b46-29b4-4a1a-884d-fcf4fa8224e2)

**Comment by minminlittleshrimp** [comment]
Hello @WouldCome 
thanks, this worth an issue.
