### ISSUE TITLE
DLT Receiver rename error and possible file loss

### ISSUE THREAD

**Issue by Laximas** [COVESA/dlt-daemon#592]
I have a device that transmits DLT traces and want to capture them. This device sometimes disconnects DLT so I have to reconnect. I am also using a file size limit. When DLT disconnects and the receiver reconnects to it, after reaching the size limit, the rename of the file has an additional increment to the number. I have built this project with cygwin so the command I use is the following:

dlt-receive.exe -a -o .\log.dlt -c 200M -p 3490 192.168.0.2

Steps to reproduce:
1. Run from cmd with a suitable size limit: dlt-receive.exe -a -o .\log.dlt -c 200M -p 3490 192.168.0.2
2. Make the device restart so the connection drops
3. When restarted, run again: dlt-receive.exe -a -o .\log.dlt -c 200M -p 3490 192.168.0.2
4. Wait until size limit is reached

This should be reproducable in a linux environment as well

**Comment by minminlittleshrimp** [comment]
Hello @Laximas 
Thanks for the report.
We will test from our side.
Kindly push your fix and we will work together.
Thank you

**Comment by Laximas** [comment]
Commit is pushed and linked to this issue, thanks!
