### ISSUE TITLE
The dlt offline storage did not work when the DLTConnectionType is DLT_CONNECTION_CLIENT_MSG_TCP

### ISSUE THREAD

**Issue by AnswerZhao** [COVESA/dlt-daemon#605]
The dlt-daemon is running on the Android CVD emulator, which acts as a guest OS on the Linux OS. When I send a DLT message using the dlt-example-user tool (using an inet socket) on Linux, the dlt-example-user tool displays "Connected to the server. Ready to send Message! Send ......". However, the offline storage file does not contain the DLT message. When I run the dlt-example-user tool to send messages on Android, it works fine.

Upon comparing the differences, I found that the key difference lies in the DLTConnectionType. When it is set to DLT_CONNECTION_CLIENT_MSG_TCP, the offline storage does not work. However, when it is set to DLT_CONNECTION_APP_MSG, the DLT logs are successfully saved to the file. Can you please help me understand why this is the case? Thank you.

**Comment by michael-methner** [comment]
Hello @AnswerZhao ,
can you attach a full log of your reproduction scenario?
Including how do you start the commands, how have you configured it. Which tag of DLT are you using? do you have any additional patches on top of it?

I wonder about the message  "Connected to the server. " the string is not located in the source code of DLT.  How do you tunnel the messages from dlt-exampler-user through inet socket?

**Comment by AnswerZhao** [comment]
@michael-methner Thanks for your reply. I had resolved it. The key is the gateway and 2 working dlt-daemon on each device. I only run the daemon on the android not on linux and use changed dlt-example-user to connect daemon with tcp.
