### ISSUE TITLE
Contribute to DLT Daemon

### ISSUE THREAD

**Issue by eaj40** [COVESA/dlt-daemon#612]
I want to gain  experience working in Dlt Daemon ,
Is there scope for continued wok

**Comment by minminlittleshrimp** [comment]
@eaj40 Hello
not sure but you can start your first step into DLT by following the documents.

For further topics then you can choose inside the tab Pull requests, many interesting topics there 😀

Discussion tab is also a good place to start your insight DLT.

Regards
Minh

**Comment by eaj40** [comment]
scope for continued work, not sure, is it correct
I am not employed can contribute to dlt daemon

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

________________________________

**Comment by eaj40** [comment]
Can i do feature implementation

**Comment by minminlittleshrimp** [comment]
Hello @eaj40 
If you can come up with any idea for new features such that improve, enhance DLT, then we are welcome to review.

For available features you can check Pull Requests, there are some features that we have not had time yet to check and reivew: dlt ring buffer rotating, dlt multinode reconnection with TCP keep alive signal, etc

Happy coding!
Minh
