### ISSUE TITLE
Do FreeRTOS supports DLT Logging 

### ISSUE THREAD

**Issue by puliviswanath** [COVESA/dlt-daemon#623]
Hi,
I need dlt-daemon for freertos, I'm trying with freeRTOS MSVC demo examples and tried creating a task that executes the dlt-daemon, I also tried different method but facing alot of errors

I want to know whether the dlt-daemon support for freeRTOS if yes, guide me through a detailed steps to configure or create project with dlt-daemon for freeRTOS

**Comment by minminlittleshrimp** [comment]
Hello @puliviswanath 
but you can give it a try, I think.

**Comment by minminlittleshrimp** [comment]
Hello @puliviswanath 
I can run successfully Arm cortexM3 MPS2 demo (using QEMU), so I will stick to this demo.
**Status:** Demo done, implementing DLT into Demo
**Issue:** DLT build fail with arm toolchain, cannot fully compiled, RCA is in progress
