### ISSUE TITLE
How to run DLT by init.rc automatically on Android

### ISSUE THREAD

**Issue by sd17464** [COVESA/dlt-daemon#636]
I need help for porting DLT on Android:
Now dlt-daemon and dlt-logd-converter run manually on Android system successfully.
But it doesn't work with init.rc automatically.
I tested on AOSP12.
Does anyone share the experience？
Thank you~

**Comment by minminlittleshrimp** [comment]
Hello @sd17464 ,

There are .rc files for dlt components:
https://github.com/COVESA/dlt-daemon/blob/master/src/daemon/dlt-daemon.rc
https://github.com/COVESA/dlt-daemon/blob/master/src/android/dlt-logd-converter.rc
Have you tried adding these rc files to vendor/etc/init/ ?

The init.rc I believe need to be set correctly to the set of init partition it belongs to:
https://android.googlesource.com/platform/system/core/+/master/init/README.md

Regards

**Comment by sd17464** [comment]
This issue has already been resolved.I'll close it.
I appreciate your time~
