### ISSUE TITLE
On Qnx，Setting the parameter GzipCompression=on will cause problems with the dlt-logstorage-ctrl display configuration file

### ISSUE THREAD

**Issue by hush-soul** [COVESA/dlt-daemon#645]
1.no problems storing uncompressed files
2.The same configuration file was successfully compressed in the Linux system

![1](https://github.com/COVESA/dlt-daemon/assets/173775795/a9a2f2cf-5818-43d0-82e0-5350459c2e9a)
![2](https://github.com/COVESA/dlt-daemon/assets/173775795/81dfc8b8-51c3-49ae-ba97-461469bf816f)

Looking forward to your reply, thank you

**Comment by minminlittleshrimp** [comment]
Hello @hush-soul 
I believe in my fix the value for parsing in ON.
Kindly testing with the latest dlt version.
Also, I wonder if it does not happen with ON_SPECIFIC_SIZE, we might look into the differences/mechanisms behind this sync behavior and the normal mode ON_MSG.
A possible issue might come from the fsync phase.
Regards

**Comment by minminlittleshrimp** [comment]
Besides, is this a duplicated one of https://github.com/COVESA/dlt-daemon/issues/644 ?

**Comment by hush-soul** [comment]
> Hello @hush-soul I believe in my fix the value for parsing in ON. Kindly testing with the latest dlt version. Also, I wonder if it does not happen with ON_SPECIFIC_SIZE, we might look into the differences/mechanisms behind this sync behavior and the normal mode ON_MSG. A possible issue might come from the fsync phase. Regards

The same situation will occur with ON_SPECIFIC_SIZE and ON_MSG

I found some phenomena. It may be a problem with my zlib. It is still being debugged. Thanks for the reply.

**Comment by hush-soul** [comment]
> Hello @hush-soul I believe in my fix the value for parsing in ON. Kindly testing with the latest dlt version. Also, I wonder if it does not happen with ON_SPECIFIC_SIZE, we might look into the differences/mechanisms behind this sync behavior and the normal mode ON_MSG. A possible issue might come from the fsync phase. Regards

I have solved this problem. It was my mistake. The qnx program code was not synchronized to the latest version. Thank you.

**Comment by hush-soul** [comment]
The new version does not have this problem

**Comment by minminlittleshrimp** [comment]
I see, thanks for the report.
My pleasure to support you 😀
