### ISSUE TITLE
Log file generated has junk characters inbetween

### ISSUE THREAD

**Issue by ManikandanChockaling** [COVESA/dlt-daemon#669]
I see junk characters as below when i try to use offline logging.

![image](https://github.com/user-attachments/assets/3360a464-04bc-4160-b2d5-23c2d71b6e87)

config used is as below

[FILTER1]
LogAppName=LCM
ContextName=.*
LogLevel=DLT_LOG_INFO
File=LCMG
FileSize=10000
NOFiles=10
SyncBehavior=ON_MSG

**Comment by lti9hc** [comment]
Hello @ManikandanChockaling,
Could you share the dlt.conf file?

**Comment by minminlittleshrimp** [comment]
Hello @ManikandanChockaling 

There is a field for setting max counter loop for file in logstorage in dlt.conf file:
```
# Wrap around value for log file count in file name (Default: UINT_MAX)
# OfflineLogstorageMaxCounter = 999    
```

The max value can be obtained here is UINT_MAX, which as far as I know is 65535.
Could you check this point from your side?
Thanks

**Comment by minminlittleshrimp** [comment]
Close for now, kindly reopen anytime
