### ISSUE TITLE
Multiple Issues with dlt-daemon.service: System not booted with systemd, Configuration Errors, and Permission Issues

### ISSUE THREAD

**Issue by Fiyeovio** [COVESA/dlt-daemon#673]
I am experiencing issues with the dlt-daemon.service on my system. The daemon fails to start correctly, and I receive several errors in the logs. Despite multiple attempts to troubleshoot, the problem persists. Below are the details of the error logs and the steps I have taken so far.

**Error Logs:**
![Screenshot_select-area_20240801125730](https://github.com/user-attachments/assets/8c77b66a-12de-4266-922d-1b9d825b43af)

**Steps Taken to Resolve the Issue:**
1.Checked the configuration of /lib/systemd/system/dlt-daemon.service and changed the user to dltuser to avoid the nobody user configuration warning.

2.Verified that the system is booted with systemd by running ps -p 1 -o comm= and confirming it returns systemd.

3.Ensured that the /tmp/dltpipes directory exists and has the correct permissions by running:
$sudo mkdir -p /tmp/dltpipes
$sudo chmod 777 /tmp/dltpipes

4.Verified the installed DLT daemon version is 2.18.6 STABLE by running dlt-daemon --version.

5.Created a dedicated user and group dltuser with the following commands:
$sudo useradd -r -s /bin/false dltuser
$sudo groupadd dltuser
$sudo usermod -aG dltuser dltuser

6.Updated the */etc/systemd/system/dlt-daemon.service* file:
>[Unit]
Description=GENIVI DLT logging daemon
After=network.target

>[Service]
ExecStart=/usr/local/bin/dlt-daemon -d
Restart=on-failure
User=dltuser
Group=dltuser
Environment=DLT_DAEMON_IGNORE_SYSTEMD_BOOT=true

>[Install]
WantedBy=multi-user.target

7.Started the service and checked its status:
$sudo systemctl daemon-reload
$sudo systemctl enable dlt-daemon.service
$sudo systemctl start dlt-daemon.service
$sudo journalctl -u dlt-daemon.service

**System Information:**
    OS: Ubuntu 22.04.4 LTS x86_64
    dlt-daemon Version: 2.18.6 STABLE

I have tried everything to the best of my ability to resolve these errors but have not been successful. Any assistance or guidance on this issue would be greatly appreciated.

**Comment by minminlittleshrimp** [comment]
Hello @minminlittleshrimp 
2.18.6 is quite an old version.
Have you tested yet with 2.18.10?

**Comment by lti9hc** [comment]
There is no response from @Fiyeovio, so I close this issue
You could reopen it in the future if you want to discuss
