### ISSUE TITLE
missing /tmp/dltpipes/dlt8545

### ISSUE THREAD

**Issue by magic-tab-01** [COVESA/dlt-daemon#675]
during test, i found the log can not be saved, after i analyze, i found the dltpiple(/tmp/dltpipes/dlt8545) has been deleted,
is there any mechanism that will delete them?

**Comment by minminlittleshrimp** [comment]
Hello @magic-tab-01 

the pipe with format pipe+<pid> in dltpipe is for injection message sending from daemon to the dlt user. So if the process killed, the pipe will be removed.

Could you kindly check at that time the process with corresponding pid is still alive?

**Comment by minminlittleshrimp** [comment]
Hello @magic-tab-01 
I close this Issue for now, feel free to reopen when it is convenient for you
