### ISSUE TITLE
Why is zero assigned to null pointer?

### ISSUE THREAD

**Issue by aitazhixin** [COVESA/dlt-daemon#676]
https://github.com/COVESA/dlt-daemon/blob/358ab0879dd27b40a9ba4c411c86f7f017e989b5/src/lib/dlt_user.c#L82
In the macro, pointer *p is NULL. Then, in the next line, 0 is assigned to *p.
What is the reason?

**Comment by michael-methner** [comment]
It's to make the application crash in case of fatal logs (if the feature is enabled, default=off).

Details can be found in the corresponding commit message: https://github.com/COVESA/dlt-daemon/commit/fc91110918e948b006fdd18d9851a95c00fc95c3

**Comment by aitazhixin** [comment]
@michael-methner Thanks. Get it.
