### ISSUE TITLE
Log level control is not fully supported for multiple user processes with the same APID

### ISSUE THREAD

**Issue by zhaoxin39913** [COVESA/dlt-daemon#690]
Hi DLT experts,

In our user case, we may have multiple user processes with the same APPID and CTXID. However according to the code investigation, the dlt-daemon doesn't save all pids of the user processes that register to the same APPID in dlt-daemon, instead it only saves the pid of the last registration process for a given APPID in the userList. It means the log control level or injection message sent to that APPID only affects the last user process.

It seems like a bug, we would expect all the processes registered to the same APPID are influenced with log level control message. Is it possible to have it fixed in the upcoming release ?

**Comment by alexmohr** [comment]
At the moment this is by design in dlt-daemon, as it's an *application* id not not a domain id, thus it's a 1:1 mapping. For now it probably would be best to fix your implementation.

**Comment by zhaoxin39913** [comment]
Thanks for your clarification. I will assign a unique APPID for each our process.
