### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by Leon-Zhang** [COVESA/dlt-daemon#701]
I have made some changes to dlt-convert.c to fulfill some useful functions, can I pusblish the modified source code on my personal github account?

**Comment by minminlittleshrimp** [comment]
MPL 2.0 is a weak copyleft, and you can modify for your own play.

Read more at: https://www.mozilla.org/en-US/MPL/2.0/

**Comment by lti9hc** [comment]
i close this, Minh already provide some information
