### ISSUE TITLE
Filter option not working

### ISSUE THREAD

**Issue by stefanbie** [COVESA/dlt-daemon#712]
Hi!
I have tried to use the filter option to filter out lines with a specific Application id. I added a file (filter.txt) where I added one line:
UDSV
Then I ran DLT_DAEMON_TCP_PORT=3491 dlt-receive -a 169.254.4.10 -f filter.txt
but I still got all the loggs.
Am i doing something wrong?

**Comment by lti9hc** [comment]
Hello @stefanbie,
For using filter option in dlt-receive, you have to add AppID and ContextID in filter file
you are missing contextid
You should run command dlt-receive -h to get more information

**Comment by stefanbie** [comment]
Hi @lti9hc, thanks for your answer! I read this help instruction and thought that "TEST" was an AppId
https://github.com/COVESA/dlt-daemon/blob/master/doc/dlt-receive.1.md#Space-separated-filter-file
So, its not possible to have ContextID as a wildecard?

**Comment by lti9hc** [comment]
Hi @stefanbie,
Currently, it does not support wildcard

**Comment by stefanbie** [comment]
Ok, @lti9hc, thanks again for the answer!
